### ISSUE TITLE
Transforming for-await loops to the configured target environment is not supported yet

### ISSUE THREAD

**Issue by prasad-anecure** [floydspace/serverless-esbuild#100]
support for esbuild with for wait

**Comment by olup** [comment]
Can you elaborate a little?

**Comment by floydspace** [comment]
Hi @prasad-anecure.

As [esbuild documentation](https://esbuild.github.io/content-types/#javascript) says:

> These syntax features are currently always passed through un-transformed:
> Syntax transform | Unsupported when --target is below | Example
> -- | -- | --
> Asynchronous iteration | es2018 | for await (let x of y) {}
> Async generators | es2018 | async function* foo() {}
> BigInt | es2020 | 123n
> Hashbang grammar | esnext | #!/usr/bin/env node
> Top-level await | esnext | await import(x)

Please forward this issue to `esbuild` repository
