### ISSUE TITLE
Importing .graphql files?

### ISSUE THREAD

**Issue by kennandavison** [floydspace/serverless-esbuild#106]
Hi - when saying "without imports", do you mean imports in the .graphql file or importing .graphql files? Trying to see if I can load a .graphql schema into a function call: https://github.com/floydspace/serverless-esbuild/issues/102

**Comment by floydspace** [comment]
I mean imports in `.graphql` files, so if you have a single `.graphql` file it works.

**Comment by kennandavison** [comment]
Got it and you can just directly import the .graphql file like this after you add the loader? import schema from './file.graphql'

**Comment by floydspace** [comment]
Yes but keep in mind that it will be bundled as a `string`, so you will have to `parse` your `schema` variable and then put it to graphql server

**Comment by kennandavison** [comment]
Got it, thanks!
