### ISSUE TITLE
Esbuild watch with sls offline not working

### ISSUE THREAD

**Issue by ipauler** [floydspace/serverless-esbuild#108]
Hello.
I've added a watch pattern in esbuild config
```
watch:
      pattern: [ 'src/**/*.ts']
```
it's recompiling code after changes, but those changes are not working
like if i add `console.log('hello')` it will recompile but i won't see that console.log() anywhere
same for other changes

**Comment by joelpickup** [comment]
Are you certain it's not this long standing issue with serverless-offline (https://github.com/dherault/serverless-offline/issues/864) ?

Enabling `--useChildProcesses` fixes this.

**Comment by ipauler** [comment]
@joelpickup thank you will check 
looks like it

**Comment by ipauler** [comment]
using childProcess flag helps, but after rebuild i have cold start which is not useful in my case 
anyway thanks, i'll be waiting for some fixes on serverless-offline side

**Comment by olup** [comment]
I'll close this. Feel free to reopen if you need more help or find bugs on this lib's side.

**Comment by henrypenny** [comment]
> --useChildProcesses

Detected unrecognized CLI options: "--useChildProcesses".

**Comment by abhijeet-toptal** [comment]
try `--reloadHandler` with serverless offline

**Comment by deviant32** [comment]
still not working for me with reloadHandler

**Comment by naydichev** [comment]
also not working for me!
