### ISSUE TITLE
Sourcemap not showing actual error stack trace 

### ISSUE THREAD

**Issue by ipauler** [floydspace/serverless-esbuild#109]
I've enabled source maps, but all errors stacktrace still points to bundled minified file which is not readable
i've tried `sourcemap: inline / enabled /true ` 
tried adding `--enable-source-maps`  to NODE_OPTIONS env in serverless config and tried passing it directly before launching sls offline 
maybe i'm missing something ?
(sorry guys i know i'm creating too many issues, just trying to get it working correctly)

**Comment by cfraz89** [comment]
Also having this issue. Similar config with serverless-esbuild shows mapped traces, but upon swapping to esbuild, sourcemaps don't seem to work.

**Comment by Mihailoff** [comment]
If you download the deployment package directly from AWS Lambda, there is not `.map` file.

**Comment by olup** [comment]
@ipauler @cfraz89 did the proposed solution worked for you ? @floydspace if this is the way to embed the source map we should maybe add this to the doc ?

**Comment by ipauler** [comment]
@olup i'm using `sourcemap: true` and `source-map-support` npm package which is doing everything that i need 
so i think issue can be closed
thanks all
