### ISSUE TITLE
Plugin breaks with serverless 2.36.0

### ISSUE THREAD

**Issue by taschmidt** [floydspace/serverless-esbuild#117]
After upgrading serverless to the just-released version 2.36.0, started receiving the following error:
```
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:124:11)
      at Object.join (path.js:1039:7)
      at new EsbuildPlugin (<project dir>/node_modules/serverless-esbuild/dist/index.js:48:33)
```

The problem appears to be dependence on the `serverless.config.servicePath` prop here:
https://github.com/floydspace/serverless-esbuild/blob/753e4aede6e826adc77cf82847520f1f84f9bef8/src/index.ts#L75

This appears to have been renamed in 2.36.0:
https://github.com/serverless/serverless/releases/tag/v2.36.0

**Comment by olup** [comment]
Thx a lot for reporting !
