### ISSUE TITLE
Name of lambda function causing issue when esbuild is packaging files

### ISSUE THREAD

**Issue by danielhorne** [floydspace/serverless-esbuild#128]
Hi Team

Firstly this is an awesome plugin.

This is an issue/feature request

When I try package my serverless project I get the following issue  _Error: ENOENT: no such file or directory, open 'C:\Users\****\repos\databus-serverless\.esbuild\.serverless\r-#{AWS::AccountId}-npr-ds-databus-hello.zip'_

The issue comes about because I am trying to add a prefix to my lambda name using the serverless-pseudo-parameters plugin. 
I have pasted my serverless config below
If I remove the _name_  field from the lambda config then your library defaults to the object property in the serverless config.

```
{
    service: "databus-serverless",
    frameworkVersion: "2.35",
    provider: {
        name: "aws",
        tags: globalTags,
        profile: "developerrole",
        region: "eu-west-1",
        runtime: "nodejs14.x",
        lambdaHashingVersion: 20201221,
        deploymentBucket: {
            name: "${self:custom.prefix}-global-auto-scaling-s3",
        },
        environment: {
            NODE_PATH: "./:/opt/node_modules",
        },
    },
    custom: {
        accountId: "#{AWS::AccountId}",
        account: "${opt:account, self:custom.accountId}",
		esbuild:{
			bundle:true,
			minify:false,
			sourcemap:true
		},
        region: "${opt:region, self:provider.region}",
        stage: '${opt:stage, "npr"}',
        prefix: "r-${self:custom.account}-${self:custom.stage}-ds-databus",
    },
    package: {
        excludeDevDependencies: true,
        individually: true
    },
    plugins: [
	"serverless-esbuild",
        "serverless-pseudo-parameters",
        "serverless-deployment-bucket",
        "serverless-offline",
    ],
    functions: {
        Hello: {
			name: "${self:custom.prefix}-hello",
            handler: "functions/hello/index.handler",
            role: "arn:aws:iam::${self:custom.account}:role/${self:custom.prefix}-iam-lambda-bifrost-role",
            layers: [
                "arn:aws:lambda:${self:custom.region}:${self:custom.account}:layer:modules:1",
            ]
        }    
  }
}
```

Is there or could there be a flag to enable this naming functionality. For example by default the build folders are named using the object property rather than the name field in function definition. In order to use the lambda name for the build folders there would be an options as follows:
```
esbuild:{
  useLambdaName:true
}
```

**Comment by floydspace** [comment]
Hi @danielhorne , could you please check, does the fix work for you. I decided not to add a new option, but simply do not use a custom lambda name if it is defined.

**Comment by danielhorne** [comment]
Hi @floydspace working perfectly, thanks
