### ISSUE TITLE
External devDependencies are included into the bundle

### ISSUE THREAD

**Issue by philiiiiiipp** [floydspace/serverless-esbuild#135]
I have uncovered some odd behaviour when bundling external dependencies. In our case it would always include dev dependencies into the build. I have dug a bit and found:

https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L78

which in our case would use the package.json of serverless-esbuild instead of the projects package.json. I am wondering if this should not actually be
```ts
  const packageJson = require(rootPackageJsonPath);
```

Because if

```ts
if (!packageJson.devDependencies || !packageJson.devDependencies[externalModule.external]) {
        prodModules.push(externalModule.external);
      } else {
```

refers to the package.json of serverless-esbuild it would add all dev dependencies, at least it does in our case.

Our setup looks like this:

```
node_modules
src
 - api
 -- serverless.yml

 - api2
 -- serverless.yml

 - api3
 -- serverless.yml

package.json
package-lock.json
```

**Comment by floydspace** [comment]
Hi @philiiiiiipp . as you could see the `packageJsonPath` is resolved as searching up from the current working directory, [see](https://github.com/floydspace/serverless-esbuild/blob/2fc9bb4a6a8f56b0885656bfd6fbb41656d47ac8/src/pack-externals.ts#L204), so it should not resolve the serverless-esbuild package.json unless your working directory is inside your node_modules serverless-esbuild folder. I would suggest to play with `packagePath` option.
And for me your setup looks not like it's typically used, maybe there is some issue. it would be good if you provide a minimal reproducible implementation, so we could cover this example. Thank you for the issue

**Comment by olup** [comment]
@philiiiiiipp do you still have your issue ? Is there a setup that we could reproduce ? Or should we close this ?
