### ISSUE TITLE
esbuild plugin onEnd is called for every Lambda function

### ISSUE THREAD

**Issue by ffxsam** [floydspace/serverless-esbuild#146]
I have two functions in a test serverless config:

```
  functions: { hello, bye },
```

And I have this in my esbuild plugin code:
```js
    build.onEnd(args => {
      console.log('### onEnd args:', args);
    })
```

When I deploy, I see this output from my plugin:

```
### onEnd args: {
  errors: [],
  warnings: [],
  outputFiles: [
    {
      path: '/Users/samh/foo/.esbuild/.build/src/functions/hello/handler.js.map',
      contents: [Uint8Array],
      text: [Getter]
    },
    {
      path: '/Users/samh/foo/.esbuild/.build/src/functions/hello/handler.js',
      contents: [Uint8Array],
      text: [Getter]
    }
  ]
}
### onEnd args: {
  errors: [],
  warnings: [],
  outputFiles: [
    {
      path: '/Users/samh/foo/.esbuild/.build/src/functions/bye/handler.js.map',
      contents: [Uint8Array],
      text: [Getter]
    },
    {
      path: '/Users/samh/foo/.esbuild/.build/src/functions/bye/handler.js',
      contents: [Uint8Array],
      text: [Getter]
    }
  ]
}
```

From the name `onEnd`, I'd assume this would just be executed once when the entire build process is done, with a complete list of files. Is there some way to achieve this?

**Comment by olup** [comment]
Hi ! Esbuild is run on each function, so your esbuild plugin is run every time. I am not sure of what you are trying to achieve in your `onEnd` hook, but it might be better suited for a serverless plugin more than an esbuild one. Serverless offers many hooks for every steps of the bundling / packaging / deploying process where you can run some plugin's code - so you can trigger code after every function is built and packaged.

**Comment by ffxsam** [comment]
@olup Thanks!
