### ISSUE TITLE
findProjectRoot trickles up out of Project Files

### ISSUE THREAD

**Issue by tonyt-adept** [floydspace/serverless-esbuild#161]
Excuse my ignorance, as this could very well be a problem with my use of the package - but I'm encountering an issue when trying to bundle my Externals with `serverless-esbuild`. Also apologies for the long winded explanation - the examples kept cropping up as I went...

Relevant scope of `serverless.ts`:
```
esbuild: {
    bundle: true,
    minify: false,
    plugins: 'esbuild-plugins.ts'  // exports esbuild-node-externals
    packager: 'npm',
    packagePath: path.join(__dirname, 'package.json')
}
```

The error I receive when running `serverless offline` or `serverless deploy` is as follows:

```  Error: ENOENT: no such file or directory, open '/Users/atyrrell/package.json'```

Another relevant aspect of the stack trace is:

``` EsbuildPlugin.<anonymous> (/Users/atyrrell/my-project/node_modules/serverless-esbuild/dist/pack-externals.js:156:55)```

Upon doing some debugging with that file - I'm wary of the way `findProjectRoot` looks for the directory - specifically with the `findUp` [function](https://github.com/floydspace/serverless-esbuild/blob/master/src/utils.ts#L85): 

The main issue being - I believe that it doesn't recover well after not finding a `yarn.lock` file. I've tried just using Yarn instead, but issues with grabbing Packages from a private registry opens a different can of worms.

FWIW - here's a my local Project structure, and a little flow of the `findProjectRoot` execution:
```
Users/
   atyrrell/
      Projects/
          sub-project/
             project_x/
                serverless.ts
                package.json
                package-lock.json
                <other project files...>           
```

I believe the trigger is here: https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L214
however I'm looking at the `/dist` files...

Looking for the `rootPackageJsonPath` results in looking for the following (filename, directory) being hit in `findUp`:
```
yarn.lock /Users/atyrrell/Projects/sub-project/project_x
yarn.lock /Users/atyrrell/Projects/sub_project
yarn.lock /Users/atyrrell/Projects
yarn.lock /Users/atyrrell
```

Then it goes quiet and complains about not being able to open `/Users/atyrrell/package.json`. It almost seems like the Directory path isn't being reset back down when it starts looking again?

Ironically this line: https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L217 
doesn't seem to be accurate, as [packageJsonPath](https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L218) actually DOES contain the value I'd expect of `/Users/atyrrell/Projects/sub_project/project_x/package.json`, but rootPackageJsonPath DOESN'T.

A bit longwinded, and hopefully not too scatter brained - I appreciate any input or info, if this is a confirmed issue I'm happy to throw up a PR. Just wanted to confirm it's not User Error!

**Comment by tonyt-adept** [comment]
FWIW I've been able to confirm the issue locally adding some Jest tests to the serverless-esbuild project, and I've introduced a fix as well. Don't seem able to push my branch up though - but that's probably because I'm an Open Source newb.

Let me know if you're interested in it!

**Comment by olup** [comment]
Hey thanks for the fix ! To propose a PR you have first to clone the repo, make a branch, commit, and then from the GitHub UI you can propose your branch as a PR onto the original repository.

**Comment by tonyt-adept** [comment]
Thanks for the info @olup!

Here she blows: https://github.com/floydspace/serverless-esbuild/pull/162

Some comments in there regarding the "fluff" I introduced with my singular Jest test.. let me know how you guys would like to proceed!
