### ISSUE TITLE
Can't bundle *.graphql files

### ISSUE THREAD

**Issue by ftschopp** [floydspace/serverless-esbuild#169]
Hello!
First of all i have to say that i am not sure if it's a bug really. Probably i missing something of configuration. The problem occurs when i build a project with `apollo-server-lambda` and in this project includes some `.graphql` files. Theses files aren't included in .build folder. So the error is the following:
```
Unable to find any GraphQL type definitions for the following pointers
/.esbuild/.build/src/graphql/schema.graphql
```
these `.graphql` isn't in that build folder.
How can i bundle these kind of files?
Thanks!

**Comment by floydspace** [comment]
Hi @ftschopp , you can use [`esbuild`'s loader](https://esbuild.github.io/api/#loader)
so your `serverless.yml` would look like:
```
custom:
  esbuild:
    loader:
      .graphql: text
```
this will bundle your `.graphql` file in the output as text

Important note: if you're using .graphql imports, it would not work, cause `esbuild` does not have appropriate instructions. in this case you have to implement some `esbuild` plugin, but it is out of the scope of this library.

**Comment by ftschopp** [comment]
@floydspace thanks for your answer! 👍🏻
