### ISSUE TITLE
[Request] serverless-offline usage example

### ISSUE THREAD

**Issue by shierro** [floydspace/serverless-esbuild#18]
Hi! Is it possible to include a sample app using this plugin, that has plays well with serverless-offline? I tried to use and got this error

![ScreenShot_20200625160036](https://user-images.githubusercontent.com/12129589/85680617-0c71ff00-b6fd-11ea-9554-732c6e41fab9.png)

**Comment by shierro** [comment]
i'm using v5 of serverless-offline
"serverless-offline": "5.12.1"

and is testing using the http endpoint provided by serverless-offline w/c is something like this

http://localhost:3000/2015-03-31/functions/cb-backend-boilerplate-lambda-staging-signupAttempt/invocations

**Comment by floydspace** [comment]
Hey @shierro . Have a look in the example folder, I updated it with `serverless-offline` usage. It's pretty straightforward, you just install both plugins and declare them in `serverless.yml` in a certain order, no need extra configuration.

According to your screen, probably you configured esbuild custom section not correct, please provide your code to help me figure out what is the issue.

**Comment by shierro** [comment]
thanks @floydspace for the quick response! I'll test this when I get the chance
