### ISSUE TITLE
build option is strangely merged

### ISSUE THREAD

**Issue by uneco** [floydspace/serverless-esbuild#19]
serverless.yml
```
custom:
  esbuild:
    target: es2019
```

command
```shell
$ sls package
```

output:
```
  Error --------------------------------------------------

  Error: Invalid target: "e,s,2,0,1,7,9" (valid: esnext, es6, es2015, es2016, es2017, es2018, es2019, es2020)
```

Online Reproducibility Demo is [Here](https://runkit.com/embed/zc9mh1xc7omv)

**Comment by uneco** [comment]
## case 2

serverless.yml
```
custom:
  esbuild:
    packager: yarn
```

output:
```
  Type Error ---------------------------------------------

  TypeError: Cannot read property 'cli' of undefined
```

This error is caused by [this line](https://github.com/floydspace/serverless-esbuild/blob/master/src/packagers/index.ts#L38).
contents of `message` is `Could not find packager 'n,p,m,y,a,r'`.

**Comment by floydspace** [comment]
Hey @uneco , thank you for your report, indeed it's a bug, I checked and seems #18 also caused by the same issue
