### ISSUE TITLE
Feature: Allow to configure plugins

### ISSUE THREAD

**Issue by doktor500** [floydspace/serverless-esbuild#206]
Hi,

I've managed to set up the `serverless-esbuild` plugin to use `esbuild-plugin-tsc` since I have code in my serverless functions that is using decorators. 

My `serverless.yml` looks like this:

```yaml
...
custom:
  esbuild:
    bundle: true
    minify: false
    plugins: esbuild-plugins.js
```

The `esbuild-plugins.js` file

```javascript
const esbuildPluginTsc = {
  name: "esbuild-plugin-tsc",
  setup(build) {
    
  }
};

module.exports = [esbuildPluginTsc];
```

And for reference the `tsconfig.json` file 

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": ["es2018"],
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "rootDirs": ["fakes", "src", "scripts", "test"],
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "types": ["jest", "node"],
    "skipLibCheck": true
  },
  "exclude": ["node_modules"]
}
```

The issue that I have is that I need to enable a flag on `esbuild-plugin-tsc` for it to work and I haven't found a way to do it.

What I would like to achieve is something similar to how plugins work on [serverless-stack](https://github.com/serverless-stack/serverless-stack/blob/3df14e42b643f4472b543a45d85ed19f707e8c19/packages/cli/test/nodejs-build-bundle-esbuildconfig/esbuild-config.js#L8) where instead of defining the name of the plugin, we can import it and configure it to set flags like "force: true".

Is this something that I can currently achieve? If not would it be possible to support this feature?

**Comment by mishabruml** [comment]
Hi @floydspace I also have a requirement on using the plugin (to get around needing `emitdecoratormetadata` flag) but am struggling to get my lambda running when using `serverless-esbuild` and `esbuild-plugin-tsc` together. Any help would be appreciated! Thanks
