### ISSUE TITLE
Confused as to how to structure shared code

### ISSUE THREAD

**Issue by kaihendry** [floydspace/serverless-esbuild#210]
My goal is to produce fast deployments **without layers**, that work locally, and where my final functions only contain the dependencies they need.

Normally I would create a package.json in each function like so:
https://github.com/kaihendry/sls-deps-esbuild/blob/main/v1/foo/bar/package.json

But that fails with `v1/foo/util/log.js:1:20: error: Could not resolve "lambda-log"`. I'm not sure how to work around that.

If I instead have package.json at the root containing all depedencies the entire service uses, I'm confused because the exported "minimal-example-dev-nolog" [zip file contains both functions](https://s.natalian.org/2021-10-15/minimal-example-dev-nolog-b4e50c7e-13bf-47a4-81ab-cdae9090601f.zip), despite setting `individually: true` upon https://github.com/kaihendry/sls-deps-esbuild/tree/individually

What is best practice here please?

**Comment by arpadgabor** [comment]
Try adding the following to your config file:

```
custom:
  esbuild:
    bundle: true
```

This is what I am doing and splits all the functions into their own zip file. But please beware, if you are trying to use packages like knex (that dynamically import other packages), you will either need to use layers, or explicitly add the [dependecies to the bundle](https://www.serverless.com/framework/docs/providers/aws/guide/packaging#patterns).

**Comment by samchungy** [comment]
Closing, please reopen if you still have an issue @kaihendry
