### ISSUE TITLE
Support Multiple Runtimes (Python/NodeJS) in same serverless.yml

### ISSUE THREAD

**Issue by simonireilly** [floydspace/serverless-esbuild#225]
Currently esbuild wants to also compile my python code.

### Steps to replicate

```
  typescript-lambda:
    handler: ./src/typescript/lambda.handler
  python:
    handler: ./src/python/lambda.handler
    runtime: python3.9

$ yarn sls package

Serverless: Compiling to node14 bundle with esbuild...
Cannot locate handler - ./src/python/lambda not found
 
 Error ---------------------------------------------------
 
  Error: Compilation failed. Please ensure you have an index file with ext .ts or .js, 
  or have a path listed as main key in package.json
```

### Proposed Solution

- Ignore any files that have entry points, where the runtime is not `nodejs.xx.x`; this will prevent esbuild attempt to compile them.
- This ignore should include not adding node_modules to the zip file created for those

**Comment by samchungy** [comment]
Just checking - are you on the latest version? @simonireilly

**Comment by shichongrui** [comment]
I am having this issue as well while trying to run `sls invoke local` for my python function. Can confirm I am on the latest `serverless-esbuild` version. If I comment out the plugin line for `serverless-esbuild` in my `serverless.yml` file it works. Uncomment it and it doesn't work.

**Comment by samchungy** [comment]
Thanks guys, I'll take a look some time in the next 24 hours.

**Comment by samchungy** [comment]
Hey @shichongrui @simonireilly, just gave it a shot and can't replicate it. (Also tried with Python3.9). Am I missing something?

![image](https://user-images.githubusercontent.com/18017094/141031528-cc4d398e-685d-4afb-8ce4-22d84f5d26e9.png)

**Comment by shichongrui** [comment]
@samchungy I've set up a local project to match your screenshot that I have attached as a zip. One note is that I don't see a `python.py` file in your screenshot. Running `sls package` does indeed succeed but if you unzip the `hello-world.zip` the python function is not packaged. Also if you run `sls invoke local -f world -d "{}"` you get the error that I am seeing.

```
Traceback (most recent call last):
  File "/Users/me/.nvm/versions/node/v14.17.0/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/runtimeWrappers/invoke.py", line 72, in <module>

    module = import_module(args.handler_path.replace('/', '.'))
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'python'
```
[python-test.zip](https://github.com/floydspace/serverless-esbuild/files/7509425/python-test.zip)

**Comment by samchungy** [comment]
Right, so your issue is different to @simonireilly's.

Your issue:
So not including the python function in the package is **intentional** as we are using esbuild to bundle the code We want to include the bare minimum to reduce the size. If you want to include the python file in the bundle you should be able to use package patterns to include it in the zip.

@simonireilly:
I couldn't quite replicate the behaviour you posted above. Let me know if you're using some different configuration.

**Comment by simonireilly** [comment]
Sure thing, I am using:
 
 ​    ​"serverless"​: ​"​2.61.0​"​,
 ​    ​"serverless-esbuild"​: ​"​1.18.1​"​

There is nothing more in my setup for bundling.

First and foremost I guess I need to update to latest and see if I am still getting the issue.

If I does stop throwing the error, I would still need the python code to bundle. I assume the if used:

```
package:
  individually: true
```

I'll get one python .zip and one JavaScript .zip that should work.

I'll let you know 👍

**Comment by samchungy** [comment]
yep ignoring node functions got added in v1.20.0. https://github.com/floydspace/serverless-esbuild/releases/tag/v1.20.0

**Comment by simonireilly** [comment]
Sure thing, this certainly is not an issue in v1.21.1.

This issue can be closed :+1:

@samchungy thanks for your support on this one, I should have read the release notes :+1:

@shichongrui to package the python I ended up with the following:

```yaml
service: serverless-225

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x

package:
  individually: true

functions:
  typescript:
    handler: index.handler

  python:
    handler: python.handler
    runtime: python3.8
    package:
      exclude:
        - node_modules/**
        - "**/*"
      include:
        - python.py
```


[serverless-esbuild-1-21.1.zip](https://github.com/floydspace/serverless-esbuild/files/7510618/serverless-esbuild-1-21.1.zip)

**Comment by samchungy** [comment]
No problemo, glad I could help. Hope you have a good day 🙂

@shichongrui if you have any other issues, feel free to open a new issue

**Comment by shichongrui** [comment]
Ok I'll open another issue for the local invocation issue.
