### ISSUE TITLE
V3 support

### ISSUE THREAD

**Issue by arpadgabor** [floydspace/serverless-esbuild#233]
Hey there,

Serverless just [announced Serverless V3](https://www.serverless.com/blog/serverless-framework-v3-beta), and it seems there aren't any major breaking changes for plugins.

This looks like the new documentation: https://www.serverless.com/framework/docs/guides/plugins/creating-plugins

**Comment by arackaf** [comment]
Hi - does anyone know if Serverless v3 is compatible with this plugin? The OP says v3 has no breaking changes, but this issue is labeled with enhancement.

**Comment by samchungy** [comment]
> Hi - does anyone know if Serverless v3 is compatible with this plugin? The OP says v3 has no breaking changes, but this issue is labeled with enhancement.

Might be good to go, haven't had the chance to try it. Let us know 😄

**Comment by samchungy** [comment]
Just gave it a quick spin on a repo or two and it should be compatible @arackaf. Let me know otherwise.

**Comment by arackaf** [comment]
@samchungy hey cool - will do. Sorry, wasn't trying to be lazy - I saw this issue was open, and had the enhancement label, so I thought maybe there was a known incompatibility. 

Will give it a go hopefully soon.
