### ISSUE TITLE
Super super super slow to create Zip files

### ISSUE THREAD

**Issue by chearmstrong** [floydspace/serverless-esbuild#234]
I have 20+ small functions.

```JavaScript
esbuild: {
  packager: 'npm',
  bundle: true,
  minify: false,
  sourcemap: false,
  treeShaking: true,
  nativeZip: true, // 👈 this helps a little but still very slow - in fact without it it mostly fails but with no meaningful error
  concurrency: 10, // 👈 makes no difference
  external: ['migrate-mongo', 'pdfkit', 'pdf-lib', 'jsonwebtoken'],
}
```

Running on a Mac:

![image](https://user-images.githubusercontent.com/10651067/142381844-d1d3cfbc-808b-4ae0-b23b-a6637b722895.png)

Any ideas?

I've also noticed that the generated Zip files are all the same size - this seems weird but it looks like it's putting everything in the Zip. Am I missing something here?

**Comment by samchungy** [comment]
Use the Serverless packaging feature if you would like them to be packed individually. Hope that helps

```
package:
  individually: true
```

**Comment by chearmstrong** [comment]
> Use the Serverless packaging feature if you would like them to be packed individually. Hope that helps
> 
> ```
> package:
>   individually: true
> ```

Hi, sorry - I should have mentioned, I'm already using that. It creates the individual Zip files. It's a fairly large project with a lot of lambdas - the Zip creation is just very very slow (`serverless-bundle` and `serverless-webpack` is fine for this step and creates Zips quite quickly).

With regards to the file sizes - is it right that all Zips are the same size. I would expect not due to tree shaking and different code being used in each, but maybe I'm missing something.

**Comment by samchungy** [comment]
Okay I have a number of questions:

1. Are the Serverless Webpack zips larger or smaller?
  a. Do you declare those modules as external for webpack too?
  
2. Have you looked at what is being being bundled in the zips?

3. Are you using any package patterns?

**Comment by chearmstrong** [comment]
OK, so I've excluded a number of packages that we deploy as a Lambda layer and this has _seems_ to have fixed the issues with the speed - the slowness only seems to be when they are included.

Looking at the zip files, `serverless-webpack` files sizes are smaller, and vary in size. `esbuild` ones are larger an all the same.

It seems top be putting all functions in the zip.

![image](https://user-images.githubusercontent.com/10651067/142881522-23a75eb1-41d0-4630-b5f1-aacf53c72095.png)

This is the package config:

```
  package: {
    individually: true,
    excludeDevDependencies: false,
    exclude: ['node_modules/**'],
  },
```

**Comment by samchungy** [comment]
That is.... strange. I see your package config is specified in typescript/js or json? Is esbuild maybe including that file..?

**Comment by samchungy** [comment]
> Yeah, our Serverless config is defined in `.js` - we export the object (which should be fine to do). The other included functions aren't imported/required between each other. It's just the functions that are included in the Zip too - no config or anything, just the built/minified JS.
> 
> No options on the individual functions. Just the config in the root.

Hmm is it possible to send a minimal repo to reproduce this?

**Comment by chearmstrong** [comment]
@samchungy I've found the issue. I haven't drilled in to the exact reason, but understand why.

My handler paths are defined with `./` at the start - this caused all the files to be bundled. Removing that solves the issue and only the required file is bundled in the Zip.

**Comment by samchungy** [comment]
Good find! That might be related to how we find the entry points since we have to grab the function by splitting

eg. function1.handler means we need to grab the `function1` file. So I think we may need to adjust how we find that to allow for the `./` operator.
