### ISSUE TITLE
Package Individually breaks if lambda paths are prefixed with ./

### ISSUE THREAD

**Issue by arackaf** [floydspace/serverless-esbuild#235]
Absolutely LOVE this plugin. Truly amazing, and a massive improvement over webpack.

Unfortunately the package individually option has stopped working. Basically this issue: https://github.com/floydspace/serverless-esbuild/issues/79 

Except it's broken again.

---

For anyone coming here with the same problem: your best workaround will be to just deploy each function individually in a custom npm script.  Ie

```
sls deploy function -f func1 && sls deploy function -f func2 && sls deploy function -f andSoOn
```

---

EDIT

This only happens when you have paths prefixed with `./`, ie

```
handler: ./handlers/scanBook.handler
```

whereas

```
handler: handlers/scanBook.handler
```

works perfectly.

**Comment by samchungy** [comment]
Hey @arackaf, could you provide an example repo? Could be related to https://github.com/floydspace/serverless-esbuild/issues/234#issuecomment-981750955 ?

**Comment by arackaf** [comment]
@samchungy oh. my. god. Yep, that was it. If the paths to the lambdas are prefixed with ./ then it completely breaks the individual packaging.

I'm good to go, but, this does still seem like a bug. I'll clarify the title but feel free to close it if this is now a duplicate of the other issue.
