### ISSUE TITLE
Loaders for particular file extensions

### ISSUE THREAD

**Issue by mjyocca** [floydspace/serverless-esbuild#237]
Want to use the Base64 loader for particular file extensions.

I see how to implement plugins, but don't see any way to pass any loader flags to esbuild via this plugin

https://esbuild.github.io/content-types/#base64

**Comment by samchungy** [comment]
I'm fairly sure we just pass through options to esbuild. Does this work?

```
custom:
  esbuild:
    loader: .data=base64
```

**Comment by mjyocca** [comment]
@samchungy I'll give that a go! 

I got it working via a custom plugin, `build.onLoad({ filter }, async (args) => {...})`

**Comment by samchungy** [comment]
Gonna close this ticket, please yell out if this is not resolved
