### ISSUE TITLE
`dotenv` looks in the wrong directory with `invoke local`

### ISSUE THREAD

**Issue by mattisdada** [floydspace/serverless-esbuild#241]
This is an odd quirk in difference in how `serverless offline` works vs `serverless invoke local ...` today.

If using the `dotenv` package, it will look for the `.env` file in `<root>/.env` in `offline`. Alternatively, in `invoke local` it will look for it in `<root>/.esbuild/build/.env` instead. 

The current working directory for the two methods appears to be different, I think this is caused by this PR: https://github.com/floydspace/serverless-esbuild/pull/122 but I am unsure...

**Comment by samchungy** [comment]
It's because we call `chdir` in here:

https://github.com/floydspace/serverless-esbuild/blob/273a3a68f1d1cf3f1d12382e1859d31f2bd453d2/src/pre-local.ts#L8

**Comment by mattisdada** [comment]
Is doing that the right thing to do? Should `serverless offline` work like that too? It's just a bit confusing that both of these work differently. 

Intuitively I would've expected the current directory to be the same on both (probably the location of the file being executed), but I might be missing a big reason why this works the way it does today

**Comment by samchungy** [comment]
Hmm can I understand how you are using dotenv in this lambda? Are you packing this .env file into the lambda? If so it makes sense that we check the build folder of the lambda for the .env file.

**Comment by mattisdada** [comment]
No, it's only for the developer environment. It's so you can have a local set of environment variables as a file, once deployed into production the env variables will be set specifically for that environment. So it's not part of the package or deployment. 

If you're unfamiliar with dotenv, this might help a little bit on why it exists:
https://github.com/motdotla/dotenv#faq

**Comment by samchungy** [comment]
> No, it's only for the developer environment. It's so you can have a local set of environment variables as a file, once deployed into production the env variables will be set specifically for that environment. So it's not part of the package or deployment.
> 
> If you're unfamiliar with dotenv, this might help a little bit on why it exists: https://github.com/motdotla/dotenv#faq

Gotcha, I am familiar with how it's used, but, I was just checking how you were intending on using it.

I'm not sure how to answer this one. I would probably recommend https://www.serverless.com/plugins/serverless-dotenv-plugin or using their native resolution to be honest. https://www.serverless.com/framework/docs/environment-variables#support-for-env-files .

I would say that having it look in the `<root>/.esbuild/build/.env` folder is more representative of an offline lambda test as you would not expect the `.env` file to be in the actual deployment.

**Comment by mattisdada** [comment]
I guess that's true, but shouldn't `serverless offline` have the same directory then? I think that's my main concern, is that there are two ways of executing this locally, but the "current directory" for both is different. Maybe that's fine though...

98% of the time I'm using `serverless offline` and it does work as expected, so no issues on that front

**Comment by samchungy** [comment]
Yeah that's a good point.

I think that might also be related to how `serverless offline` works. Since `serverless invoke local` targets a single specific lambda but with `serverless offline` we have no idea what lambda will be invoked and we rely on the behaviour of the `serverless-offline` plugin.

So like you suggested that might just be a quirk between the two. Bare in mind both implementations do explicitly state that they are not a 100% perfect emulation but a good enough one.
