### ISSUE TITLE
Package Individually Doesn't Work Properly After v1.22.1

### ISSUE THREAD

**Issue by randalvance** [floydspace/serverless-esbuild#243]
After v1.22.1, package individually seem to not work properly.

This repo can be used to replicate this:
https://github.com/randalvance/serverless-typescript-reference

First change the version of `serverless-esbuild` in `package.json` to `1.22.0`. 
Run `npm run build`. Inside `.serverless` folder, check the individual function's zip file content and notice that only the code for that single function is included.

Update to version `1.22.1` , do an `npm i` and `npm run build`.
Inside `.serverless` folder, check the individual function's zip file content:

**Expected Behaviour**
The individual zip files should only contain the code for a single function.

**Actual Behaviour**
The individual zip files contain code for all the other functions.

This bug seems to still be present in v1.23.0.

OS: Windows 10
NodeJS Version: 14.17.5

**Comment by samchungy** [comment]
Probably something related to the relative paths logic, what does your path to the handler resolve to in the end? @randalvance 

Eg. hello.handler

**Comment by samchungy** [comment]
Hey @randalvance I just tried your sample repo and I'm not noticing anything different between the builds. Can I check what OS you are running on? I'm on a mac.

When I ran `npm run build` the zips had only 1 handler each?

![image](https://user-images.githubusercontent.com/18017094/145704532-9341e4be-7b64-4e0f-8eac-319df756669e.png)

**Comment by samchungy** [comment]
Okay looking at your code I see you're using Windows for your development. I'll fix this probably later this week but do yourself a favour and install WSL 😆.

**Comment by randalvance** [comment]
@samchungy, did you changed the version to 1.22.1 first? I also tried this in my Mac.

**Comment by samchungy** [comment]
> @samchungy, did you change the version to 1.22.1 first? I updated the repo to use the problematic version so you can just pull the latest change.
> 
> ~I also tried this in my Mac.~ I previously can replicate this also in my Mac, weirdly not anymore. I added the OS and NodeJS versions in the description.

Yeah, I replicated it on Windows but could not on OSX. I'll fix it during the week if I have time.

**Comment by randalvance** [comment]
Thanks @samchungy, verified working now.
