### ISSUE TITLE
getDepsFromBundle does not work when using esbuild-node-externals

### ISSUE THREAD

**Issue by dillon-sellars-voya** [floydspace/serverless-esbuild#245]
getDepsFromBundle assumes that all dependencies are present in the minified bundle. when using esbuild-node-externals, this is not the case as the nested dependencies are resolved from each dependency inside node_modules in separate require statements. As a result the list of dependencies passed to flatDep contains is incomplete and several libraries are not included in the .zip. 

I believe this is why serverless-webpack creates a temporary project with the top-level dependencies in a package.json that it creates and runs npm / yarn install on that to get the full complete node_modules needed to support the bundle.

**Comment by samchungy** [comment]
Did this PR resolve your issue? https://github.com/floydspace/serverless-esbuild/issues/103

**Comment by samchungy** [comment]
Should be resolved by https://github.com/floydspace/serverless-esbuild/pull/267. Let me know if this isn't the case :)
