### ISSUE TITLE
`patterns` not working as expected for me - files missing from `.zip`

### ISSUE THREAD

**Issue by chearmstrong** [floydspace/serverless-esbuild#246]
Hi.

Using version `1.23.1`.

I'm trying to get some files included in my deployment bundle - I have these files in `migrations-core` alongside my serverless function handlers.

![image](https://user-images.githubusercontent.com/10651067/146164714-989d41c3-5681-439e-87d1-d07fb2c0f3b3.png)

On these functions only, I have this:

```JavaScript
package: {
  patterns: ['**/migrations-core/*'],
},
```

When the code is being bundled, I can see these `__only` folders with the files and it refers to the the 2 expected functions.

![image](https://user-images.githubusercontent.com/10651067/146165282-424024e9-10f0-4cd2-becc-20f1311bce90.png)

However, these files are never included in the `.zip` file.

Am I missing something here - how can I get these files included? This is my config.

```JavaScript
  esbuild: {
    bundle: true,
    minify: true,
    treeShaking: true,
    sourcemap: false,
    nativeZip: true,
    concurrency: 20,
    external: ['mongoose', 'winston', 'migrate-mongo', 'pdfkit', 'pdf-lib'],
    format: 'cjs',
},
```

**Comment by chearmstrong** [comment]
Just to update on this - I have found the issue and a possible fix. I just wanted to make sure that it is indeed a bug and I'm not misunderstanding something.

The issue is this logic [here](https://github.com/floydspace/serverless-esbuild/blob/master/src/pack.ts#L68).

This logic check is `true`, therefore the files are excluded as the if block it returns `false`. Seems to be due to `fnNameWithoutStage` (which doesn't include stage - `sos-lambdas-core-uk-DBMigrateUpCore`) and the files in my case do include the stage. For example in my case `__only_sos-lambdas-core-uk-qa-DBMigrateUpCore/uk/functions/db-migrations/migrations-core/some-file.js`.

As a fix, passing in [`name`](https://github.com/floydspace/serverless-esbuild/blob/master/src/pack.ts#L163) to the `filterFilesForZipPackage` function and using that instead works and the files are included as expected.

```JavaScript
    if (localPath.startsWith('__only_') && !localPath.startsWith(`__only_${name}/`))
      return false;
```

Am I right in my thinking - is it a bug or is this expected behaviour?

**Comment by samchungy** [comment]
Sorry I haven't had my computer on me for the past week, I still don't. I was gonna take a look.

Looks related to the change here. https://github.com/floydspace/serverless-esbuild/pull/229

If you click through to the linked issue I think @capaj mentions that the stage is not present on local?

Can I check what version of serverless you are on?

**Comment by chearmstrong** [comment]
> Sorry I haven't had my computer on me for the past week, I still don't. I was gonna take a later this week
> 
> Looks related to the change here. #229
> 
> If you click through to the linked issue I think @capaj mentions that the stage is not present on local?
> 
> Can I check what version of serverless you are on?
> 
> Perhaps there's a difference when you pass in the stage versus if you don't? What command so you use to package?

The command is:

```bash
SLS_DEBUG=* LOCALE=uk AWS_REGION=eu-west-1 AWS_ACCOUNT_ID=159902525747 STAGE=qa NODE_OPTIONS=--max_old_space_size=6096 npm run build:uk -- --stage=qa
```

The `npm run build:uk` script is just `cross-env LOCALE=uk serverless package --locale=uk`.

Severless version - `2.30.3`.

**Comment by chearmstrong** [comment]
I've taken a look at that PR - I don't use `serverless-offline` but to me, that PR breaks things. It might resolve the `serverless-offline` issue but breaks the build/package.

Even when I don't specify a stage manually in `serverless.yml` the folder is created with a stage (`dev`). I'm not sure why it wouldn't?

**Comment by samchungy** [comment]
Think I've figured it out in the above PR @chearmstrong ^

**Comment by chearmstrong** [comment]
Nice one - yeah, that makes more sense.
