### ISSUE TITLE
Does not use settings passed to node externals plugin

### ISSUE THREAD

**Issue by domdomegg** [floydspace/serverless-esbuild#250]
The esbuild-node-externals plugin's configuration options do not seem to have any effect in combination with serverless-esbuild.

My esbuild-plugins.js:

```
const { nodeExternalsPlugin } = require('esbuild-node-externals');

module.exports = [nodeExternalsPlugin({
  allowList: ['@a/package']
})]
```

My serverless.ts contains:

```
esbuild: {
  minify: true,
  plugins: "./esbuild-plugins.js",
}
```

However, `@a/package` is then packed as an external module which it shouldn't be.

I believe this might be because serverless-esbuild detects whether the plugin is enabled, but then overwrites the settings with an empty allowlist:

https://github.com/floydspace/serverless-esbuild/blob/8a1dcc02c49574c0b04df084a3b79049b4e8e25f/src/pack-externals.ts#L220

My current workaround is to pack all external modules, but this appears to make my lambda functions slower.

**Comment by samchungy** [comment]
Just to let you know, I did see this a while ago but I was busy trying to fix the external packaging. I'll take a look some time in the next week :)

**Comment by samchungy** [comment]
Okay so it looks as if we cannot access the options you add to the plugin. The plugin itself relies on us calling the setup() function it returns however our plugin doesn't do that.

We could possibly give it it's own little section under our esbuild config. 🤔 

Eg.

```
custom:
  esbuild:
    node-externals:
      allowList:
        - package
```
