### ISSUE TITLE
Retain file/directory structure

### ISSUE THREAD

**Issue by doteric** [floydspace/serverless-esbuild#254]
I'm trying to figure out a way to retain the build file structure. I don't want everything bundled into one file.

First of all when I disable the `bundle` I get this error:
```
Cannot use "external" without "bundle"
```
I can omit that by simply specifying `exlucde: []`, but that doesn't help in anything, because there is only one entryPoint and it doesn't look like I can include all my files.
Any solutions to this?

Thanks

**Comment by samchungy** [comment]
Hello this is an issue thrown by Esbuild so we cannot help you here.

**Comment by doteric** [comment]
@samchungy , so is there any other way to use serverless-esbuild and retain the file structure?
