### ISSUE TITLE
[info] Wondering about size comparing to webpack

### ISSUE THREAD

**Issue by jlgouwyapizr** [floydspace/serverless-esbuild#257]
Hey folks ! 

Currently I'm using webpack 4 coupled with serverless-webpack.
The bundle time is quite long and that frustrates me.
So I came to take a look at esbuild.

But after trying serverless-esbuild on another branch, I find that my function size is twice as heavy.
On the other hand, for the bundle time is very very fast.

I then wonder if I am doing something wrong or if esbuild is less efficient in terms of compression ?

Here are the sizes of my packages with esbuild (options bundle+minify on true).

```
Serverless: Uploading service F1.zip file to S3 (302.82 KB)...
Serverless: Uploading service F2.zip file to S3 (254.18 KB)...
Serverless: Uploading service F3.zip file to S3 (259.81 KB)...
Serverless: Uploading service F4.zip file to S3 (132.59 KB)...
Serverless: Uploading service F5.zip file to S3 (149.04 KB)...
Serverless: Uploading service F6.zip file to S3 (241.16 KB)...
Serverless: Uploading service F7.zip file to S3 (277.35 KB)..
```

VS webpack 4 : 

```
Serverless: Uploading service F1.zip file to S3 (178.65 KB)...
Serverless: Uploading service F2.zip file to S3 (137.7 KB)...
Serverless: Uploading service F3.zip file to S3 (140.8 KB)...
Serverless: Uploading service F4.zip file to S3 (78.58 KB)...
Serverless: Uploading service F5.zip file to S3 (80.17 KB)...
Serverless: Uploading service F6.zip file to S3 (137.74 KB)...
Serverless: Uploading service F7.zip file to S3 (145.47 KB)...
```

thanks for your feedbacks

**Comment by floydspace** [comment]
Hey @jlgouwyapizr 
Thank you for this valuable comparison.
Could you please check what causes the difference inside archives: the node_modules folder size or the bundle file size?

**Comment by jlgouwyapizr** [comment]
Hey 

I bundle everything. For now, I didn't use externals yet. 

I see the difference by watching inside ./.serverless folder after running : 
```
sls package
```

**Comment by jlgouwyapizr** [comment]
This my webpack config, webpack.config.js : 
```
const slsw = require('serverless-webpack');

module.exports = {
    entry: slsw.lib.entries,
    mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
    target: 'node',
    optimization: {
        minimize: true
    },
 ```
 
 and for esbuild, just in serverless.yml :
 ```
 esbuild:
  bundle: true
  minify: true
 ```

**Comment by floydspace** [comment]
Unfortunately, we cannot help much here, because bundling is completely done by `esbuild`, the `serverless-esbuild` is just a wrapper around it + externals packaging layer. As long as you're not using externals it is not an issue of this plugin.
I found this issue in `esbuild` repo maybe it would b helpful https://github.com/evanw/esbuild/issues/958

**Comment by jlgouwyapizr** [comment]
Oh interesting ! Thanks for the feedback !
