### ISSUE TITLE
ESM Format Support

### ISSUE THREAD

**Issue by RichiCoder1** [floydspace/serverless-esbuild#258]
With [Lambda support for ESM](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/), it'd be awesome to be able to opt into ESM output format. Bonus points for being dynamic (since `serverless-offline` still only supports cjs, but prod bundles would want to be ESM)

**Comment by samchungy** [comment]
Enabling support could be an easy one?

Could probably just remove this line
https://github.com/floydspace/serverless-esbuild/blob/09f08c738171ed7e7b50727bef1846e9b0bcf579/src/index.ts#L290

and make it a default option. Should be a non-breaking change.
https://github.com/floydspace/serverless-esbuild/blob/09f08c738171ed7e7b50727bef1846e9b0bcf579/src/index.ts#L56

Not sure how I would feel about defaulting it to `cjs` just for `serverless-offline` though.
