### ISSUE TITLE
Use Serverless V3 logging

### ISSUE THREAD

**Issue by fargito** [floydspace/serverless-esbuild#259]
Hello ! Thanks for this awesome project :)

Serverless V3 came out last week and comes with a new logging system which produces cleaner output.
https://www.serverless.com/framework/docs/guides/plugins/cli-output

I think it would be great to use the same policy for this plugin, what do you think ? I can look into it and submit a PR in the next days.

**Comment by floydspace** [comment]
Hi, @fargito thank you for the suggestion, I think it is a good idea, but keep in mind that the plugin can be still used with older versions of SLS, down to V1, not sure how these changes would affect the behavior, I will leave it to you. But PRs are welcome

**Comment by samchungy** [comment]
I think this would force us to set a minimum version of serverless framework to v3 by the looks

**Comment by samchungy** [comment]
Oh it looks like this is possible without a breaking change to previous versions

https://github.com/serverless-heaven/serverless-webpack/pull/1013/files
