### ISSUE TITLE
External dependencies bundling issue with version 1.23.4+

### ISSUE THREAD

**Issue by EugeneDraitsev** [floydspace/serverless-esbuild#265]
Hi

I have an issue after update from version 1.23.3 to 1.23.4
It seems like this update breaks external modules bundling

I have 1 external module:

```yml
    external:
      - sharp
```

This module has `color` dependency and `color` has `color-string` dependency. So I would expect to see both modules in the `/node_modules` folder. However with version 1.23.4 it seems like only top level dependencies are copied to final build:

v1.23.3 with external `sharp`:
![image](https://user-images.githubusercontent.com/16540432/152703769-34ce50ea-1798-4e77-af67-64d0926d34aa.png)

v1.24.4+ with external `sharp`:
![image](https://user-images.githubusercontent.com/16540432/152703691-7babcd33-921f-43a8-98ec-7547c1b9b3dc.png)

I think it can be related to this changes in 1.23.4: https://github.com/floydspace/serverless-esbuild/commit/91f283f587c3e005aa884dc528c82c3f82bca6c8 but I'm not sure about it

**Comment by samchungy** [comment]
🙈  Bugger, I'll look to adding some e2e tests to cover this some time in the future. Can I ask you what package manager you are using?

**Comment by EugeneDraitsev** [comment]
Hi, I'm using yarn `1.22.17`

**Comment by samchungy** [comment]
Okay don't mind me but I'm going to use this space to take some notes. Okay interestingly `yarn` has a dependency on ^4.2.0 and if we look in the dependency tree ^4.2.0 has an empty dependency tree but 4.2.0 has the dependency tree. This appears to affect only `yarn` at the moment. I'll probably have to go give pnpm a shot later on.

I'll see if I can resolve this over my lunch break.

yarn:
![image](https://user-images.githubusercontent.com/18017094/152705613-7ae90f8a-c579-4b71-a567-3dd4f56c50f0.png)

npm:
![image](https://user-images.githubusercontent.com/18017094/152705665-051a968f-7474-48ed-ab81-af67521556a5.png)
![image](https://user-images.githubusercontent.com/18017094/152705654-051b76a0-630a-4a11-9ba5-883e68d1b7c5.png)

**Comment by samchungy** [comment]
Update on this:

It turns out that yarn packaging is incredibly complex. Unlike `npm` which simply places version numbers the yarn output contains `^`, `~`, `*`, `1.x` in their version syntax which will involve more work than the simple mapping logic which `npm` packagers can use.

**Comment by samchungy** [comment]
Reverted these changes for now. Thanks for raising the issue @EugeneDraitsev. Much appreciated.
