### ISSUE TITLE
Does not bundle externals

### ISSUE THREAD

**Issue by kobanyan** [floydspace/serverless-esbuild#268]
Does not bundle externals when the import module name is different from the external package name.

Please see [example](https://github.com/kobanyan/serverless-esbuild-issue).

**Comment by samchungy** [comment]
Hey @kobanyan could you please provide more information?

What is the expected output? What is the current output? I can't see you declaring anything as external

**Comment by kobanyan** [comment]
@samchungy Thanks for the reply.

**expected behavior**
zip contains source-map-support and uuid in node_modules

**actual behavior**
zip contains uuid, but not source-map-support in node_modules

**console**
```
$ yarn sls package
Serverless: Compiling to node14 bundle with esbuild...
Serverless: Compiling with concurrency: Infinity
Serverless: Compiling completed.
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: source-map-support@0.5.21, uuid@8.3.2
Serverless: Zip function: example - 59.97 KB [63 ms]
Serverless: Packaging service...
```

Is the above information sufficient?

**Comment by samchungy** [comment]
In the above example I don't see them marked as `external`

If you want them to be included in your bundle you must mark them as such.

See https://github.com/floydspace/serverless-esbuild#external-dependencies for more information. Let me know if I am misinterpreting your issue.

**Comment by samchungy** [comment]
Oh I think I understand, A reference to `source-map-support/register` isn't importing `source-map-support` gotcha.

**Comment by kobanyan** [comment]
In the example, i use esbuild-node-externals plugin to easily mark all the dependencies in package.json as external.

I was able to work around it by rewriting import as follows.

```
- import 'source-map-support/register';
+ import { install } from 'source-map-support';
+ install();
```

However, since this problem can be noticed only after deploying or unzipping, it would be helpful if the plugin could take care of it.

**Comment by samchungy** [comment]
> In the example, i use esbuild-node-externals plugin to easily mark all the dependencies in package.json as external.
> 
> I was able to work around it by rewriting import as follows.
> 
> ```
> - import 'source-map-support/register';
> + import { install } from 'source-map-support';
> + install();
> ```
> 
> However, since this problem can be noticed only after deploying or unzipping, it would be helpful if the plugin could take care of it.

Should be a relatively simple fix, but I'll take a look after I fix up the dependency tree fix PR 😄

**Comment by samchungy** [comment]
Hey just an fyi @kobanyan. Source Maps are stable from Node.js 14.18. I recommend setting `NODE_OPTIONS=--enable-source-maps` instead of using this package.

**Comment by kobanyan** [comment]
Thanks!
