### ISSUE TITLE
e2e integration tests

### ISSUE THREAD

**Issue by samchungy** [floydspace/serverless-esbuild#281]
I think we could possibly add some e2e tests to this. Perhaps we could make use of the examples folders.

Similar to this: https://github.com/floydspace/serverless-esbuild/issues/189 but I want to make extra sure I'm not breaking the really core functionality while working on this repository eg. https://github.com/floydspace/serverless-esbuild/issues/265. At the moment I essentially do the following in my local testing.

My plan is to:

1. run `yarn build` on the repo. 
2. Either make use of `yarn link`, `npm link` or copy paste the built result into the examples folder.
3. Run `sls package`.
4. Check bundle with a snapshot.

Happy to take some other suggestions.

**Comment by mishabruml** [comment]
Happy to help out on this one if I can. Just had a look at the esbuild e2e tests for inspiration, they look a little terse https://github.com/evanw/esbuild/blob/1452a38071824872132c9c0570374d8ee0b46f60/Makefile but maybe a good starting point?

I guess we aren't really wanting to test that esbuild works, more that the project just invokes esbuild with the desired arguments etc. But I suppose in the context of e2e tests, this would be achieved by observing the side effects (i.e. a compiled project 😕 )

**Comment by mishabruml** [comment]
I had a stab at it https://github.com/floydspace/serverless-esbuild/pull/293
