### ISSUE TITLE
Slow detection of file changes

### ISSUE THREAD

**Issue by trygveaa** [floydspace/serverless-esbuild#290]
I see that when I use serverless-offline, after I write a file it takes 2-3 seconds until the new code is compiled. If I try to run a function in this time, the old code is run. This is very inconvenient because it means I need to watch the output of serverless-esbuild after I make changes and wait until I see that the compile has completed before I run the function again.

I checked out what is causing this and I see that it's the `awaitWriteFinish` option for chokidar. Is this really necessary to use? I can't recall ever having an issue with half-written files, but I suppose it may vary between machines.

I propose two fixes for this:
1. When a file is changed block requests to functions until the compilation is finished. With this I would still have to wait 2-3 seconds, but at least I wouldn't have to watch the output of esbuild and wait with performing my request.
2. Make the `awaitWriteFinish` option (and perhaps the other chokidar options) configurable.

Preferably, both of these fixes would be implemented.

Could you consider this, or would you accept a PR for this?

**Comment by samchungy** [comment]
Always happy to take PRs 😄

**Comment by deathemperor** [comment]
@trygveaa it would be nice when the new code is compiled it prints out something like `compiled with latest changes`. As of right now it's hard to know when new changes are applied.

**Comment by abhijeet-toptal** [comment]
> @trygveaa it would be nice when the new code is compiled it prints out something like `compiled with latest changes`. As of right now it's hard to know when new changes are applied.

It used to print some text like watching for file changes, recompiling with concurrency: infinity, but after the upgrade, no logs are coming and hot reload is actually not working sporadically, earlier it worked like a charm

**Comment by abhijeet-toptal** [comment]
`--verbose` flag in to serverless fixed this
