### ISSUE TITLE
The serverless-esbuild bundler fails with Typeorm/Prisma

### ISSUE THREAD

**Issue by joaocasarin** [floydspace/serverless-esbuild#305]
**Describe the bug**
When trying to create a aws lambda with typescript and try to use some ORM like Typeorm and Prisma, whenever I write `serverless deploy` or `serverless-offline`, I get the same exact error.

**To Reproduce**
Clone this repo: https://github.com/joaocasarin/aws-lambda-typeorm-error
Run `yarn install` to install dependencies and then either `serverless deploy` or `serverless offline`.
You will get the same exact error as in the below screenshot.

PS.: You will see the `typeorm` version in the branch `main`, and the `prisma` version in the branch `prisma`. Both executes as the description.

**Expected behavior**
The lambda should execute as normal: create the lambda function, expect some input from user in a POST request body, and response with the created user.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/48847394/166126309-c2cb7484-7eda-4b58-a995-6980e78af8ef.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - Serverless Framework Version: 3.14.0
 - Serverless Plugin Version: 6.2.1
 - serverless-esbuild version: ^1.26.2

**Comment by samchungy** [comment]
Have you tried marking the above libraries as external? Often this is because older libraries aren't using try/catch blocks with optional dependencies.

**Comment by joaocasarin** [comment]
> Have you tried marking the above libraries as external? Often this is because older libraries aren't using try/catch blocks with optional dependencies.

I'm not sure what you mean with that, could you elaborate how to mark them as external?

also, thanks for the quick reply ☺️

**Comment by samchungy** [comment]
> > Have you tried marking the above libraries as external? Often this is because older libraries aren't using try/catch blocks with optional dependencies.
> 
> I'm not sure what you mean with that, could you elaborate how to mark them as external?
> 
> also, thanks for the quick reply ☺️

https://esbuild.github.io/api/#external

Set is as external eg. in your serverless.yml
```
custom:
  esbuild:
    external:
      - X
      - Y
```

**Comment by joaocasarin** [comment]
> > > Have you tried marking the above libraries as external? Often this is because older libraries aren't using try/catch blocks with optional dependencies.
> > 
> > 
> > I'm not sure what you mean with that, could you elaborate how to mark them as external?
> > also, thanks for the quick reply ☺️
> 
> https://esbuild.github.io/api/#external
> 
> Set is as external eg. in your serverless.yml
> 
> ```
> custom:
>   esbuild:
>     external:
>       - X
>       - Y
> ```

I just tried that... That error is now gone, but whenever I try to reach the lambda endpoint using the `serverless offline`, I get this error:
```bash
POST /dev/create-user (λ: create-user)
× offline: one of the module nesting handler for handler handler is undefined or not exported
× Error: offline: one of the module nesting handler for handler handler is undefined or not exported
      at InProcessRunner.run (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\InProcessRunner.js:171:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async LambdaFunction.runHandler (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\serverless-offline\dist\lambda\LambdaFunction.js:369:20)
      at async hapiHandler (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\serverless-offline\dist\events\http\HttpServer.js:740:18)
      at async exports.Manager.execute (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\@hapi\hapi\lib\toolkit.js:60:28)
      at async Object.internals.handler (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\@hapi\hapi\lib\handler.js:46:20)
      at async exports.execute (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\@hapi\hapi\lib\handler.js:31:20)
      at async Request._lifecycle (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\@hapi\hapi\lib\request.js:371:32)
      at async Request._execute (C:\Users\joaov\Desktop\aws-lambda-typeorm-error\node_modules\@hapi\hapi\lib\request.js:281:9)
```

PS.: I have created a branch in the same repo called `external-fix` to reproduce this error.

**Comment by joaocasarin** [comment]
I have also tried [this solution](https://github.com/serverless/serverless/discussions/11026#discussioncomment-2668261) that basically install those packages in the main project, but I get the same error as above (not the original error).

**Comment by samchungy** [comment]
Seems like an issue with Serverless Offline now - I suggest trying something in https://github.com/dherault/serverless-offline/issues/1377

**Comment by joaocasarin** [comment]
> Seems like an issue with Serverless Offline now - I suggest trying something in [dherault/serverless-offline#1377](https://github.com/dherault/serverless-offline/issues/1377)

I'm pretty sure it's not related to Serverless Offline, since everything works fine using `serverless-webpack` instead of `serverless-esbuild`. I can share the repo, if you want.

**Comment by joaocasarin** [comment]
Any idea here?

**Comment by samchungy** [comment]
Can you try downgrading to serverless-offline 8.5.0. I'm fairly certain it's related to it.

**Comment by joaocasarin** [comment]
> Can you try downgrading to serverless-offline 8.5.0. I'm fairly certain it's related to it. I'm moving house right now so I don't have alot of time.

indeed the error changes to another... Sorry for bothering I actually hadn't tried to downgrade before. I'll be commenting on that discussion about my case, because there is still another error.

**Comment by samchungy** [comment]
> > Can you try downgrading to serverless-offline 8.5.0. I'm fairly certain it's related to it. I'm moving house right now so I don't have alot of time.
> 
> indeed the error changes to another... Sorry for bothering I actually hadn't tried to downgrade before. I'll be commenting on that discussion about my case, because there is still another error.

Had a quick look. You might need to declare bcrypt as external too unfortunately

**Comment by joaocasarin** [comment]
> > > Can you try downgrading to serverless-offline 8.5.0. I'm fairly certain it's related to it. I'm moving house right now so I don't have alot of time.
> > 
> > 
> > indeed the error changes to another... Sorry for bothering I actually hadn't tried to downgrade before. I'll be commenting on that discussion about my case, because there is still another error.
> 
> Had a quick look. You might need to declare bcrypt as external too unfortunately

Yeah! After adding bcrypt to external libs it worked... But why was that even necessary? I mean, there is no log saying to do something like that and I'm also using some others external libs such as yup and uuid, why wasn't them necessary to be added in the external entry?

**Comment by samchungy** [comment]
> > > > Can you try downgrading to serverless-offline 8.5.0. I'm fairly certain it's related to it. I'm moving house right now so I don't have alot of time.
> > > 
> > > 
> > > indeed the error changes to another... Sorry for bothering I actually hadn't tried to downgrade before. I'll be commenting on that discussion about my case, because there is still another error.
> > 
> > 
> > Had a quick look. You might need to declare bcrypt as external too unfortunately
> 
> Yeah! After adding bcrypt to external libs it worked... But why was that even necessary? I mean, there is no log saying to do something like that and I'm also using some others external libs such as yup and uuid, why wasn't them necessary to be added in the external entry?

because that library is written in a way where it's expecting package.json to be at a specific spot in your directory.

**Comment by Dilven** [comment]
To debug this, do a serverless package and check what is packaged in the zip-archive (in the .serverless directory). You can try extracting the zip-archive and do a node ./.serverless/handlers/your-handler.js then you should see more information what it's going on

**Comment by mishabruml** [comment]
I'm also having this issue, trying to use `Typeorm` with esbuild 😢 

Project compiles fine, until I import something from Typeorm into a handler.

I've got `typeorm`, `pg` and `pg-native` as externals

The `sls:package` results in a weird crash loop

```shell

> sls:package
> rm -rf .esbuild && sls package "-s" "nonprod"

Error:
RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at /Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:75:38
    at Array.forEach (<anonymous>)
    at recursiveFind (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:75:30)
    at /Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:83:17
    at Array.forEach (<anonymous>)
    at recursiveFind (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:75:30)
    at /Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:83:17
    at Array.forEach (<anonymous>)
    at recursiveFind (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:75:30)
    at /Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:83:17
    at Array.forEach (<anonymous>)

    ....etc...

    at recursiveFind (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:75:30)
    at flatDep (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/helper.js:92:5)
    at /Users/mishabruml/*****/node_modules/serverless-esbuild/dist/pack.js:140:49
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async EsbuildServerlessPlugin.pack (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/pack.js:129:5)
    at async before:package:createDeploymentArtifacts (/Users/mishabruml/*****/node_modules/serverless-esbuild/dist/index.js:83:17)
    at async PluginManager.runHooks (/Users/mishabruml/*****/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/mishabruml/*****/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/mishabruml/*****/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/mishabruml/*****/node_modules/serverless/lib/serverless.js:174:5)
    at async /Users/mishabruml/*****/node_modules/serverless/scripts/serverless.js:687:9
```

**Comment by mishabruml** [comment]
This happens even if I mark every dependency as external

**Comment by samchungy** [comment]
> This happens even if I mark every dependency as external

Ah your issue is different. Seems like I might not have covered a case in the dependency flattener. What version are you using?

**Comment by mishabruml** [comment]
```json
"serverless": "^3.1.1",
"serverless-esbuild": "^1.23.4",
"node": "^16.12.0",
"npm": "^8.1.0"
 ```
 as you'll know, node16 isn't available yet on aws lambda so its running on node14

**Comment by samchungy** [comment]
> ```json
> "serverless": "^3.1.1",
> "serverless-esbuild": "^1.23.4",
> "node": "^16.12.0",
> "npm": "^8.1.0"
> ```
> 
> as you'll know, node16 isn't available yet on aws lambda so its running on node14

Can you update to at least 1.26.2 and try again? 🙏 I think I may have resolved it in that version

**Comment by samchungy** [comment]
> ```json
> "serverless": "^3.1.1",
> "serverless-esbuild": "^1.23.4",
> "node": "^16.12.0",
> "npm": "^8.1.0"
> ```
> 
> as you'll know, node16 isn't available yet on aws lambda so its running on node14

Node16 should be available now btw? 🤔

**Comment by mishabruml** [comment]
Bundling for node 16 was fine btw @samchungy
