### ISSUE TITLE
Packaging causing antivirus alert JS.TeslaCrypt.2.Gen

### ISSUE THREAD

**Issue by ptykamikaze** [floydspace/serverless-esbuild#314]
**Describe the bug**
When running the command `serverless package` the process works fine until it is creating / copying the ZIP files since the bitdefender application is reporting that some of the zip files created by esbuild are infected.

![image](https://user-images.githubusercontent.com/5614001/169922400-de356628-0f2d-412f-9e6b-680779ee8334.png)

**To Reproduce**
Steps to reproduce the behavior. If you have an example repository that would be even better:
1. Serverless configuration
```
esbuild:
    bundle: true
    minify: false
    packager: npm
    installExtraArgs: ['--production']
    watch:
      pattern: ["src/**/*.ts"]
      ignore: ["src/**/local*.ts"]
    plugins: esbuild-plugins.js
```
3. esbuild-plugins.js content
```
const { nodeExternalsPlugin } = require("esbuild-node-externals");
module.exports = [nodeExternalsPlugin()];
```
5. Run `sls package`

The dependencies used in the project:
```
"dependencies": {
    "@maxmind/geoip2-node": "^2.3.2",
    "@middy/core": "^1.4.0",
    "@middy/http-json-body-parser": "^1.4.0",
    "@middy/validator": "^1.4.0",
    "@redtea/format-axios-error": "^2.0.2",
    "axios": "^0.21.4",
    "axios-retry": "^3.2.4",
    "countries-and-timezones": "^2.5.0",
    "crypto-js": "^3.3.0",
    "data-api-client": "^1.2.0",
    "dayjs": "^1.11.0",
    "epsagon": "^1.121.2",
    "file-type": "^14.7.1",
    "firebase-admin": "^9.12.0",
    "form-data": "^3.0.1",
    "generate-payment-card": "^1.0.8",
    "i18n-iso-countries": "^6.8.0",
    "jose": "^1.28.1",
    "json-rules-engine": "^6.1.2",
    "jsonwebtoken": "^8.5.1",
    "lambda-cache": "^1.0.0",
    "lodash": "^4.17.21",
    "nodemailer": "^6.7.3",
    "postcode-validator": "^3.6.6",
    "pubnub": "^4.37.0",
    "qrcode": "^1.5.0",
    "sightengine": "^1.3.1",
    "string-similarity": "^4.0.4",
    "twilio": "^3.76.0",
    "uuid": "^3.4.0",
    "xml2js": "^0.4.23"
  }
```

**Expected behavior**
We are trying to migration from serverless-webpack to serverless-esbuild so this should be working without any type of alert by antivirus. Currently in webpack we have no alerts. We tough this was a problem of an infected computer, but we tested in three Macbook Pro and one Windows computer

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Versions (please complete the following information):**
 - OS: Mac v12.3.1, Windows 10
 - Serverless Framework Version: 1.83.3
 - Plugin Version:
   - "serverless-esbuild": "^1.28.0",
   -  "esbuild": "^0.14.39",
   - "esbuild-node-externals": "^1.4.1",

**Additional context**
Your plugin is great!!!! We want to use it without being scared of affect our lambda zip files

**Comment by samchungy** [comment]
Sounds like you might have a malicious dependency among your deps. Are you using externals?

You could try disabling scripts when you install packages with the `installExtraArgs` option.

```
custom:
  esbuild:
    installExtraArgs:  ['--ignore-scripts']
```

If this stops the alert, I would try and find which package is causing this.

**Comment by ptykamikaze** [comment]
Hello Sam, Thanks for the quick response.... I tried with the ignore-scripts argument but the same issue... There is something interesting... If I remove the word "payment" from the function name, it is not detected as virus.....  The weird thing is that with webpack this is not happening...  I will try to create a project to check if I can replicate the issue.
