### ISSUE TITLE
How to integrate prisma with serverless framework aws-nodejs-typescript template that uses serverless-esbuild

### ISSUE THREAD

**Issue by kaykhan** [floydspace/serverless-esbuild#332]
I am building a serverless function using the serverless framework. However im having an issue with running it locally

> Error: ENOENT: no such file or directory,
> open ''/.esbuild/.build/node_modules/.prisma/client/schema.prisma'

**prisma/schema.prisma**

    generator client {
        provider      = "prisma-client-js"
        binaryTargets = ["native", "rhel-openssl-1.0.x"]
    }

**serverless.ts** 

    package: {
        individually: true,
        patterns: [
            "!node_modules/.prisma/client/libquery_engine-*",
            "node_modules/.prisma/client/libquery_engine-rhel-*",
            "!node_modules/prisma/libquery_engine-*",
            "!node_modules/@prisma/engines/**",
        ],
    },

steps:

    npx prisma generate && npm install 
    
    sls invoke local -f main

What am i doing wrong here?

**note**: 

- attempting to follow this example: https://github.com/prisma/prisma-examples/tree/latest/deployment-platforms/aws-lambda

- i am using the serverless aws-nodejs-typescirpt template which uses serverless-esbuild and not serverless-webpack

**Comment by floydspace** [comment]
Hi @kaykhan. if you're using default `serverless-esbuild` config, it will bundle everything for you in one file, but to correctly resolve .prisma schema you'll need to let esbuild know hot to treat the schema file, so could you try to define:
```yml
  esbuild:
    loader:
      .prisma: text
```
and let us know if it helps

**Comment by floydspace** [comment]
the difference would be that in my example it would put your schema in the bundle during the build step and would not demand the file in runtime.

your solution also works because you copied the schema file in the place where it's expected in runtime and resolves correctly.
