### ISSUE TITLE
esbuild config function is called with unresolved serverless param

### ISSUE THREAD

**Issue by codingnuclei** [floydspace/serverless-esbuild#334]
**Describe the bug**
 Hi,

The first time `buildOptions` getter is called it is in the constructor.
https://github.com/floydspace/serverless-esbuild/blob/2c1d2ac842ac4270c48028d123887193ae957af2/src/index.ts#L85

If I am not wrong then this causes the esbuild config to be called with an unresolved serverless object.

> Note: configuration values are only resolved after plugins are initialized. Do not try to read configuration in the plugin constructor, as variables aren't resolved yet. Read configuration in lifecycle events only.
(https://www.serverless.com/framework/docs/guides/plugins/creating-plugins)

Possible moving this logic to the `initialize` hook might solve this.

**To Reproduce**
Steps to reproduce the behavior. If you have an example repository that would be even better:
1. Set : `esbuild:    config: "./esbuild.config.js"`
2. Set an ssm import somewhere in custom `SECRET: ${ssm.eu-west-1:/domain/${self:custom.stage}/secret}`
3. `console.log(serverless)` in the config function.
4.  `SECRET` will still be an un resolved string

**Expected behavior**
`SECRET` should be the resolved value from ssm

**Versions (please complete the following information):**
 - OS: [ Mac]
 - Serverless Framework Version: [2.72.3]
 - Plugin Version: [1.31.0]

**Comment by samchungy** [comment]
Nice one, worth a fix I think. I'll have a look some time over the week

**Comment by codingnuclei** [comment]
@samchungy had a little time on hand to give this issue a go. Let me know what you think?
