### ISSUE TITLE
Support --no-build for package and deploy

### ISSUE THREAD

**Issue by martinmicunda** [floydspace/serverless-esbuild#338]
**Is your feature request related to a problem? Please describe.**
The [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack/issues/398) has option to use `--no-build` flag so we can run `npx sls webpack` that build webpack contents  and then run `sls deploy --no-build -stage qa` that should package and deploy the serverless service using the existing `.webpack` contents 

**Describe the solution you'd like**
This is the [PR](https://github.com/serverless-heaven/serverless-webpack/pull/560) that was raised for serverless-webpack. The advantage to use `--no-build` is for CI/CD where we can create single zip file and deploy the zip to each env. 

1. sls package --package ./dist
2. sls deploy --no-build --stage qa (this command still generate `cloudformation-template-update-stack.json` and `serverless-state.json` files but it uses .zip file generated in step 1)

**Comment by floydspace** [comment]
Seems like closed
