### ISSUE TITLE
work with serverless-lumigo

### ISSUE THREAD

**Issue by fabioginzel** [floydspace/serverless-esbuild#340]
**Describe the bug**
As of version 1.30.0 projects that use serverless-lumigo no longer work

**Comment by fabioginzel** [comment]
this is the result of deploy

<img width="797" alt="Captura de Tela 2022-08-02 às 10 20 51" src="https://user-images.githubusercontent.com/7377511/182384786-d1b905c8-4835-47a9-a35a-4b4447abf5f6.png">

**Comment by fabioginzel** [comment]
In 1.27.0 version the code is complete

**Comment by samchungy** [comment]
Hello, I need more info than that to help you, can you provide a sample repo or something?

**Comment by fabioginzel** [comment]
See this repository:

https://github.com/fabioginzel/serverless-esbuild-error

**Comment by samchungy** [comment]
Looks like an issue with `serverless-lumingo`. If you remove that plugin you can see we have packaged it successfully. Looks like your plugin isn't pulling in the file into the bundle.

**Comment by fabioginzel** [comment]
But with 
"serverless-esbuild": "1.29.0",
 its work

**Comment by samchungy** [comment]
Likely Lumingo is not handling relative paths https://github.com/floydspace/serverless-esbuild/releases/tag/v1.32.3. I suggest raising an issue with them.
