### ISSUE TITLE
Lambda redeployment during each pipeline run

### ISSUE THREAD

**Issue by dzmitrykliapkou** [floydspace/serverless-esbuild#346]
**Describe the bug**
We use Serverless with esbuild plugin to build and deploy a set of AWS Lambda functions. During pipeline execution Serverless is run from inside an AWS Codebuild container. We noticed that each time we run the pipeline SHA sum of Lambda zip packages is different and it causes functions to be redeployed each time

After small investigation we found that `package.json` file in each packaged module contains absolute path to esbuild directory like here:
```json
{
  "_args": [
    [
      "quick-format-unescaped@4.0.4",
      "/codebuild/output/src073731813/src/api/.esbuild/.build"
    ]
  ],
  ...
  "_where": "/codebuild/output/src073731813/src/api/.esbuild/.build",
}
```
But each time Codebuild container is created this path is different. Is there any way to avoid putting these absolute paths in `package.json`? It is very inconvenient and it increases AWS Codepipeline execution time

**To Reproduce**
- Create AWS Codepipeline with AWS Codebuild step
- Run Serverless with `serverless-esbuild` from Codebuild

**Expected behavior**
No absolute paths in `package.json` and identical SHA sum of zip packages if the code is not changed

**Versions (please complete the following information):**
 - OS: Linux
 - Serverless Framework Version: ^2.65.0
 - Plugin Version: ^1.26.2

**Comment by samchungy** [comment]
This is an npm issue tbh. Can't resolve this one.

https://github.com/npm/npm/issues/12110

**Comment by dzmitrykliapkou** [comment]
I see
Think the issue can be closed. As a workaround we decided to create additional directory with persistent path inside a codebuild container and perform build process there
Thanks
