### ISSUE TITLE
make externals dependencies work with yarn berry

### ISSUE THREAD

**Issue by valentinbeggi** [floydspace/serverless-esbuild#353]
Hi there,

**Is your feature request related to a problem? Please describe.**
Using Yarn Berry, bundling fails when using any `external` dependencies in esbuild config.
Code breaks because when `hasExternals` variable is true, commands related to yarn1 (e.g. yarn list) and not compatible with yarn berry are being invoked.

**Describe the solution you'd like**

Being able to declare `external` dependencies while using Yarn Berry.

**Describe alternatives you've considered**

I've patched the plugin so I could still bundle my lambdas with these 2 hotfixes, which are only temporary:

- In `pack.ts`
```ts
-     const packagerDependenciesList = hasExternals
-        ? await packager.getProdDependencies(this.buildDirPath)
+        const packagerDependenciesList = {}

```
- In `packagers/yarn.ts`
```ts
+        fs.writeFileSync(path.join(cwd, 'yarn.lock'), '');
         const args = useLockfile
-            ? ['install', '--frozen-lockfile', '--non-interactive', ...extraArgs]
-            : ['install', '--non-interactive', ...extraArgs];
+           ['install', ...extraArgs];
```

Sadly, it makes my lambdas .zip node_modules contain the entirety of their dependencies.

**Additional context**

If that's something you feel relevant, I would be happy to help implementing it ! 
Cheers 👋

**Comment by samchungy** [comment]
Linked to https://github.com/floydspace/serverless-esbuild/issues/327

A fair bit of refactor will need to be done to support yarn2+ and pnpm. If you have time - be my guest. Otherwise, yeah I'll have to buckle up and get it done at some point
