### ISSUE TITLE
python import issues with serverless offline

### ISSUE THREAD

**Issue by davidworkman9** [floydspace/serverless-esbuild#356]
Hi, this is a re-issue of #285.

I've taken the original reproduction upgraded to the latest version and am getting the same import errors when attempting to hit a python endpoint via API gateway: https://github.com/davidworkman9/sls-esbuild-repro

I originally ran into esbuild complaining about these two new options, which I believe the fix is to remove them from the build options before sending the options to esbuild. So I patched that using patch-package.

**Comment by samchungy** [comment]
Please update your version. It is resolved in later versions already

**Comment by davidworkman9** [comment]
This reproduction is at the version it was "resolved" at. I've also tried the latest version.

**Comment by davidworkman9** [comment]
Sorry, I guess the error message is different on the latest version.. Updated the reproduction and opened #357 with the newer error message.
