### ISSUE TITLE
Getting "✖ Bundle error, waiting for a file change to reload..." with esbuild 0.17.10

### ISSUE THREAD

**Issue by deathemperor** [floydspace/serverless-esbuild#439]
**Describe the bug**
"✖ Bundle error, waiting for a file change to reload..." error keeps showing with esbuild 0.17.10 when file changes but doesn't show on first start. New changes are not applied.

**To Reproduce**
1. Start serverless-offline
2. make changes

Reproducible repo https://github.com/deathemperor/serverless-reprodution

**Expected behavior**
No error showns

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/4255482/220253463-447e743f-3f8c-4b5e-8cf3-358cce290d1f.png)

**Versions (please complete the following information):**

- OS: Mac
- Serverless Framework Version: 3.27.0
- Plugin Version: 1.39.0

**Additional context**
Doesn't occur with esbuild 0.16.x

**Comment by floydspace** [comment]
@trygveaa could it be related to your last fix?

**Comment by floydspace** [comment]
@deathemperor according to the lately merged pr https://github.com/floydspace/serverless-esbuild/pull/438
You could try using flag 'awaitWriteFinish' in your watch config

**Comment by trygveaa** [comment]
@floydspace: No, as I commented here, it happened for me before my changes: https://github.com/floydspace/serverless-esbuild/pull/432#issuecomment-1435663290

**Comment by jlangsu** [comment]
@trygveaa Initially, I was willing to chalk it up to chokidar in the 'watch' step (in esbuild 0.17+ the esbuild watch implementation might be a better substitute)  but it looks like you were working through some issues with that with #438.

As of #432, esbuild 0.16.17 was specified for the build here. (I built locally with 0.17+, but the github actions tests failed due to peer dependency issues, so I reverted the lib to 0.16 before the PR was merged.) Without putting any time into investigating (my local build worked as well) might the issue be related to mismatched apis between the peer dependencies?

**Comment by deathemperor** [comment]
> @deathemperor according to the lately merged pr #438 You could try using flag 'awaitWriteFinish' in your watch config

I tried with

```yml
watch:
      chokidar:
        awaitWriteFinish: true
```

error still occurs

**Comment by trygveaa** [comment]
> @trygveaa Initially, I was willing to chalk it up to chokidar in the 'watch' step (in esbuild 0.17+ the esbuild watch implementation might be a better substitute) but it looks like you were working through some issues with that with #438.

This error isn't related to chokidar at all. Maybe switching to esbuilds built in watch could be considered, though it uses polling while chokidar uses events, so chokidar is probably less cpu intensive and more responsive.

> As of #432, esbuild 0.16.17 was specified for the build here. (I built locally with 0.17+, but the github actions tests failed due to peer dependency issues, so I reverted the lib to 0.16 before the PR was merged.) Without putting any time into investigating (my local build worked as well) might the issue be related to mismatched apis between the peer dependencies?

Ah, that explains why it worked for me when running locally. It used the esbuild dependency from the serverless-esbuild directory, which was still 0.16.17.

I opened #440 to fix this issue.
