### ISSUE TITLE
Error trying to use serverless-esbuild with serverless-offline on Mac M1

### ISSUE THREAD

**Issue by artur-rod** [floydspace/serverless-esbuild#454]
**Describe the bug**
I just started a serverless project using aws-nodejs-typescript template, installed the dependencies with yarn and when I try to run ``sls offline``, I'm getting this error:
````
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "@esbuild/darwin-arm64" package is present but this platform
needs the "@esbuild/darwin-x64" package instead. People often get into this
situation by installing esbuild with npm running inside of Rosetta 2 and then
trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
2 is Apple's on-the-fly x86_64-to-arm64 translation service).

If you are installing with npm, you can try ensuring that both npm and node are
not running under Rosetta 2 and then reinstalling esbuild. This likely involves
changing how you installed npm and/or node. For example, installing node with
the universal installer here should work: https://nodejs.org/en/download/. Or
you could consider using yarn instead of npm which has built-in support for
installing a package on multiple platforms simultaneously.

If you are installing with yarn, you can try listing both "arm64" and "x64"
in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.
````
**To Reproduce**
Steps to reproduce the behavior.

1. Run ``serverless create --template aws-nodejs-typescript --path ignite-serverless-challenge`` to create a new project
2. Run ``yarn`` to install the dependencies
3. Run ``sls offline``

**Expected behavior**
Expect serverless function to run offline.

**Screenshots or Logs**
<img width="966" alt="image" src="https://user-images.githubusercontent.com/72319409/227240128-7a144e82-fa33-4a37-9879-64ac34994f15.png">

**Versions (please complete the following information):**
- OS: Mac (on M1 Chip)
- Serverless Framework Version: 3.0.0
- Plugin Version: 1.17.1
- Serverless Offline Version: 12.0.4

**Additional context**
I already tried the advice on the error to set up ``os`` and ``cpu`` on a ``.yarnrc.yml`` file, and added to ``package.json``too, but no success.
Also, I changed from ``serverless.ts``to ``serverless.yml``config file.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/72319409/227241269-dec20651-1332-47df-b678-679a8baad1c9.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/72319409/227241399-78ba52d2-c705-4360-8072-e2e87e0469d9.png">

**Comment by floydspace** [comment]
Hi @artur-rod 
I don't think it's the issue of `this` plugin, but the `esbuild` bundler itself.
However, I noticed you use `node 19`, but in printed error it's stated `node 16`, kinda weird.
Could you maybe try to use `node 16` or `node 18` in your shell? And obviously reinstall dependencies.
Also, I'd suggest try `npm` instead of `yarn` just to eliminate variants

**Comment by fredrik** [comment]
Hey @artur-rod, I tried recreating your issue on my M1 Macbook but could not. It works fine with both `npm` and `yarn` for me.

I've installed Node via `nvm`, which I recommend you try if you haven't. 

For what it's worth, here are my versions in this templated project:

```
❯ npm --version
9.5.0
❯ node --version
v18.14.2
❯ yarn --version
1.22.19


❯ npm list
ignite-serverless-challenge@1.0.0 /private/tmp/ignite-serverless-challenge
├── @middy/core@3.6.2
├── @middy/http-json-body-parser@3.6.2
├── @serverless/typescript@3.29.0
├── @types/aws-lambda@8.10.114
├── @types/node@14.18.42
├── esbuild@0.14.54
├── json-schema-to-ts@1.6.5
├── serverless-esbuild@1.43.0
├── serverless-offline@12.0.4
├── serverless@3.29.0
├── ts-node@10.9.1
├── tsconfig-paths@3.14.2
└── typescript@4.9.5
```
