### ISSUE TITLE
Support ESBuild 0.18.0

### ISSUE THREAD

**Issue by cmcnicholas** [floydspace/serverless-esbuild#470]
**Describe the bug**

`package.json` defines peer dep for esbuild to `< 0.18`

**To Reproduce**

Try to update to `0.18.0` esbuild.

**Expected behavior**

To `npm install` correctly.

**Screenshots or Logs**

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: serverless-esbuild@1.43.1
npm ERR! Found: esbuild@0.18.0
npm ERR! node_modules/esbuild
npm ERR!   dev esbuild@"^0.18.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@">=0.8 <0.18" from serverless-esbuild@1.43.1
npm ERR! node_modules/serverless-esbuild
npm ERR!   dev serverless-esbuild@"^1.43.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: esbuild@0.17.19
npm ERR! node_modules/esbuild
npm ERR!   peer esbuild@">=0.8 <0.18" from serverless-esbuild@1.43.1
npm ERR!   node_modules/serverless-esbuild
npm ERR!     dev serverless-esbuild@"^1.43.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Versions (please complete the following information):**

- OS: Windows
- Serverless Framework Version: `^3.27`
- Plugin Version: `^1.43.1`

**Additional context**

N/A

**Comment by fm-sz** [comment]
This package also has a dependency to https://github.com/pradel/esbuild-node-externals

I have submitted a PR there to raise the allowed esbuild version: https://github.com/pradel/esbuild-node-externals/pull/43

Without this change, the esbuild version also can't be upgraded in this package.

**Comment by fm-sz** [comment]
After the package https://github.com/pradel/esbuild-node-externals was now upgraded with the merge of https://github.com/pradel/esbuild-node-externals/pull/43, I tried to upgrade the allowed esbuild dependency here as well: https://github.com/floydspace/serverless-esbuild/pull/473

However I ran into some issues with the `incremental` option. I don't fully understand how to solve these yet.
Help, inspiration and comments in the PR are highly appreciated.

**Comment by acommodari** [comment]
Hey just wondering what the status of this issue is? Would love to know if theres an ETA for `esbuild` 0.18

**Comment by vicary** [comment]
Gently pinging @floydspace, what is your recommended approach with the `incremental` option in #473?

**Comment by Ilia-TheNetworkFirm** [comment]
Hi guys, looks like [esbuild-node-externals](https://github.com/pradel/esbuild-node-externals) have recently published a new release: https://github.com/pradel/esbuild-node-externals/releases/tag/v1.9.0

**Comment by floydspace** [comment]
closed by https://github.com/floydspace/serverless-esbuild/pull/487
thanks to @ZachLeviPixel
