### ISSUE TITLE
pkg?.context is not a function after 491 and 492 commits

### ISSUE THREAD

**Issue by njculpin** [floydspace/serverless-esbuild#493]
**Describe the bug**
Since 9/19 builds now produce error:
TypeError: pkg?.context is not a function
.../serverless-esbuild/src/bundle.ts:104:46)
.../node_modules/p-map/index.js:57:22

i believe it's related to the two commits in the last 24 hours:
https://github.com/floydspace/serverless-esbuild/commit/0d536838329b8269a39d095f4ddde08066e7bd4a
https://github.com/floydspace/serverless-esbuild/commit/36ef92eab5485c9f6dc2ea222c97cae0330f3858

**Expected Result**
This should build properly.

**Reproduce**
"Serverless Package" to reproduce locally

Here is my package.json:
{
  "name": "manage-api",
  "version": "1.0.0",
  "description": "Serverless aws-nodejs-typescript template",
  "main": "serverless.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": ">=14.15.0"
  },
  "dependencies": {
    "@middy/core": "^2.5.3",
    "@middy/http-json-body-parser": "^2.5.3",
    "@shelf/dynamodb-parallel-scan": "^3.3.0",
    "axios": "^0.27.2",
    "csvtojson": "^2.0.10",
    "dayjs": "^1.11.6",
    "find-color": "^0.1.0",
    "gql-query-builder": "^3.8.0",
    "json2csv": "^5.0.7",
    "lodash": "^4.17.21",
    "os": "^0.1.2",
    "path": "^0.12.7",
    "request": "^2.88.2",
    "sharp": "^0.31.1",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@serverless/typescript": "^3.0.0",
    "@types/aws-lambda": "^8.10.71",
    "@types/node": "^14.18.51",
    "esbuild": "^0.14.54",
    "json-schema-to-ts": "^1.5.0",
    "serverless": "^3.0.0",
    "serverless-dynamodb-local": "^0.2.40",
    "serverless-esbuild": "^1.48.2",
    "serverless-offline": "^10.1.0",
    "serverless-plugin-split-stacks": "^1.11.3",
    "ts-node": "^10.4.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.1.3"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT"
}

**Temp Fix**
Forced previous version prior to change.

**Comment by floydspace** [comment]
Thank you @njculpin for raising it, I made a silly mistake in the previous fix.
I admit we have a test coverage issue
