### ISSUE TITLE
update esbuild peerDependency (0.20 -> 0.21)

### ISSUE THREAD

**Issue by naotama2002** [floydspace/serverless-esbuild#536]
esbuild 0.21 is out, need to update the peerDependency.

**Comment by lynxSven** [comment]
esbuild 0.22 is now out

**Comment by rion18** [comment]
esbuild 0.23 is now out :thinking:

**Comment by rion18** [comment]
oh my. serverless-esbuild gets updated and esbuild 0.24.x gets released :(

**Comment by floydspace** [comment]
I'm working on it , that was indeed a face palm moment to me
