### ISSUE TITLE
Missing dependency on @effect/schema

### ISSUE THREAD

**Issue by letharion** [floydspace/serverless-esbuild#554]
**Describe the bug**
After 081242fc, and the migration to effect, I get this error on my builds:
Error: Cannot find module '@effect/schema/Schema'

yarn add -D @effect/schema resolves the issue.
I suggest this is added as a direct dependency, or possible just added to the READMEs installation instructions.

**To Reproduce**
Build without having schema installed.

**Expected behavior**
Working build.

**Versions (please complete the following information):**
081242fc

**Comment by floydspace** [comment]
oh thanks for the issue, will fix it asap

**Comment by floydspace** [comment]
the fix is in v1.54.2
