### ISSUE TITLE
Effect compatibility issue with Node 14

### ISSUE THREAD

**Issue by bjmvercelli** [floydspace/serverless-esbuild#556]
**Describe the bug**
Support for Node 14 broke with #553 since Effect uses nullish coalescing assignment operator (??=), which is available for Node >= 15 (reference: https://node.green/#ES2021-features-Logical-Assignment-----basic-support)

![image](https://github.com/user-attachments/assets/f4b832d7-e9a5-449c-a05d-759ddeb2d102)

**Versions (please complete the following information):**

- OS: Linux
- Serverless Framework Version:3.39.0
- Plugin Version: 7.2.3

**Comment by floydspace** [comment]
yeah, it is expected, we dropped the v14 support, it's time to move on,
I can look at it if I can quickly implement transpilation to  node 14,
but for now you can use older plugin version [v1.53.0](https://github.com/floydspace/serverless-esbuild/releases/tag/v1.53.0)

**Comment by bjmvercelli** [comment]
> yeah, it is expected, we dropped the v14 support, it's time to move on, I can look at it if I can quickly implement transpilation to node 14, but for now you can use older plugin version [v1.53.0](https://github.com/floydspace/serverless-esbuild/releases/tag/v1.53.0)

Agree 100%, its time to move on haha.
I don't think that's necessary to implement transpilation to Node 14 but we could update supported runtimes on README, what you think?

**Comment by floydspace** [comment]
yes makes sense

**Comment by bjmvercelli** [comment]
Appreciate the great work. Let me know if you want me to open PR ;)

**Comment by floydspace** [comment]
@bjmvercelli just fyi added it [here](https://github.com/floydspace/serverless-esbuild/commit/b448e4371778b37eea13a3f4ed2644f97bc47f6c)
