### ISSUE TITLE
Specifying a path to the package.json

### ISSUE THREAD

**Issue by jayair** [floydspace/serverless-esbuild#80]
Hi there,

I was testing this plugin out and ran into some issue. We have a monorepo setup where the individual services do not have their own `package.json`. I noticed that this plugin uses the code from [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack). Any plans to add the ability to set your own path for the `package.json`? Or alternatively, climbing up the directories to look for a `package.json` file?

https://github.com/serverless-heaven/serverless-webpack/blob/31662103851933ac277b02119912b593c2914ece/lib/packExternalModules.js#L242 => https://github.com/floydspace/serverless-esbuild/blob/master/src/packExternalModules.ts#L151

**Comment by floydspace** [comment]
Hi @jayair . thank you for the issue
yes, it does make sense to add `packagePath` option.
I will work on it

**Comment by paulswail** [comment]
I'm using a monorepo with a single root package.json and have hit the same issue. My preference would be for the default behaviour to be to climb up directories until it finds a package.json file like the serverless-webpack plugin does.

**Comment by floydspace** [comment]
@jayair @paulswail hey guys, I added an optional `packagePath` parameter which indicates the absolute path to the package.json file to be used for packaging, if it is omitted, the package.json will be found walking up folders
Please let me know if you have any issues. thanks

**Comment by jayair** [comment]
@floydspace That's awesome. Thanks for quick response. I'll give it a test shortly. And we'll be promoting this plugin ASAP.
