### ISSUE TITLE
Avoid changing  this.serverless.config.servicePath

### ISSUE THREAD

**Issue by bboure** [floydspace/serverless-esbuild#90]
Hi!

First off, thanks for this plugin! I have been trying it and it looks awesome! A decent alternative to Webpack, indeed.

I am having compatibility issues with another plugin though (specifically with [serverless-appsync-simulator](https://github.com/bboure/serverless-appsync-simulator)). It is an offline solution for AppSync and it relies on `this.serverless.config.servicePath` in order to build some config objects.
Since the servicePath is being suffixed with `/.build`, it cannot find some files it requires.

I was wondering what was the purpose of this override? My understanding is that it is to make serverless-offline work as it is looking for the handlers in that path.
Am I missing something else?

I think it is probably a bad idea to change serverless config like such as there is always a risk to affect other plugins or the serverless implementation itself.

I'd be happy to help to find solutions and alternatives to this, but I'd like to have a better understanding of the motivations and consequences this could have.

Thank you

**Comment by floydspace** [comment]
Hi @bboure, thank you for your request. The idea of replacing the servicePath is to let serverless build correct artifact archives for deployment (we do not need to pack source code, we need the built bundle). The possible solution here could be: not replace servicePath, but prepare deployment archives ourselves. I guess it is what @olup has done with individual packaging feature. To be honest the plug-in is mostly a fork from the ’serverless-plugin-typescript’ plugin so it's heritage of it, and I agree mutating inputs is not the way how it should be done

**Comment by olup** [comment]
I agree we should try and avoid rewriting the default. The logic can stay the same, for most part. The only thing is to actually do the bundle, as @floydspace described. Even this logic can be rewired from the individual packaging that actually filters out things depending on what we package. So it should be enough to not filter anything for a global packaging. If times permits I'll send a pr this week to work this out.

**Comment by bboure** [comment]
Great. Thank you @olup 
Let me know if I can help.

**Comment by olup** [comment]
hey @bboure you can see that we have a PR here https://github.com/floydspace/serverless-esbuild/pull/93 - would you mind trying this version in your repo to see if it builds fine ?
