### ISSUE TITLE
Package individually also packages sourcemaps of other functions

### ISSUE THREAD

**Issue by kennandavison** [floydspace/serverless-esbuild#91]
https://github.com/floydspace/serverless-esbuild/pull/87 - this PR fixed the individual function packaging, but I'm noticing sourcemaps are still generated for the other functions (not the js files, just the js.map extensions).

To repro just have:

esbuild:
    sourcemap: true
package:
    individually: true

ps. thanks @olup for fixing the individual packaging bug!

**Comment by olup** [comment]
Indeed, bundling and source mapping is done once for the whole project, then files are distributed over individual artifact archives, and this is done by exclusion of files. So performance wise it's the same, however you are right we should blacklist non relevant source maps. I'll fix that today or tomorrow.
