### ISSUE TITLE
Use bestzip instead of archiver

### ISSUE THREAD

**Issue by thomaschaaf** [floydspace/serverless-esbuild#96]
https://www.npmjs.com/package/bestzip should make deployment quicker and use less memory. serverless-webpack has decided to use it too: https://github.com/serverless-heaven/serverless-webpack/pull/596/files

**Comment by olup** [comment]
Great idea ! Will add it later today or Monday.

**Comment by olup** [comment]
On second thought I am not sure about `bestzip`. The lib provides no typescript typings, even from the community. That is not a big deal in itself but it says something about the lib distribution and willingness to live up to modern standards. Its use is also quite confidential compared to `archiver` or `adm-zip`, and it hasn't been updated in 6 months. The last resolved issues date back from 2018. This is not a perfect picture.

However, a quest for the best zip lib is a good idea, only this has to be thought trought a little bit more.

**Comment by olup** [comment]
For instance, https://101arrowz.github.io/fflate/ ?

**Comment by thomaschaaf** [comment]
@olup in theory you could write the native zip command calling part yourself 🤷 there is also one more thing missing that is specifing the lastUpdatedTime to `new Date(0)`. I still feel that zipping speed is more important than getting the same hash for the zip file.

**Comment by olup** [comment]
Ok that's interesting. Improvements on the zipping would be a plus, however this is typically something that we be run once on deploy only, probably on a ci or something, and part of a process (bundle and upload to aws) that is pretty long anyway. So I wonder how much we could really benefit from a zip optimization. However every useless code should be questioned, and I am now wondering: what's the purpose of keeping the hash the same, do you know ?

**Comment by vamche** [comment]
@olup Do you want to reconsider https://github.com/nfriedly/node-bestzip, I see that the library/repo happened to have some activity in the last 3 months.

zip times seems to be a concern, we have ~60 functions and zipping takes >1000 seconds for many of them on GitLab CI.

![Screenshot 2021-06-16 at 4 30 41 PM](https://user-images.githubusercontent.com/9653338/122207995-60eb2d00-cec0-11eb-9882-374b93c74c41.png)

**Comment by olup** [comment]
Wow, yeah, I guess this *is* a concern ! I am not against changing the zip lib, quite the opposite (and I am not the one to make the call anyway), and a bit of activity on the lib is indeed reassuring. But that means we'll have to manage the typings ourselves, which I would argue against. Maybe this is a feeble con for many pros. Maybe we should try `bestzip` and benchmark performances to see how much is gained - but ideally we'd find another lib altogether that can call the native zip when available.

**Comment by vamche** [comment]
@olup Thank you, I will try to do some benchmarking, archiver vs bestzip.

@floydspace What do you think about `bestzip`?

**Comment by vamche** [comment]
So, I updated the plugin to use `bestzip` and ran some tests.  The results are impressive, `bestzip` is definitely faster than `archiver` and I think it's better to migrate to `bestzip`. Changes: https://github.com/floydspace/serverless-esbuild/pull/148

### On GitLab CI (Shared runner w/ 1vCPU, 4GB RAM)
**w/ `archiver` (maximum ~1240s)**
![Screenshot 2021-06-17 at 1 59 51 PM](https://user-images.githubusercontent.com/9653338/122361631-1081d700-cf75-11eb-8faf-a2b3e018190e.png)

**w/ `bestzip` (maximum ~500s)**
![Screenshot 2021-06-17 at 2 00 44 PM](https://user-images.githubusercontent.com/9653338/122361688-1d062f80-cf75-11eb-92be-7f7b0c0d9dd0.png)


### On my local (M1, 16G RAM)
**w/ `archiver` (maximum ~219s)**
<img width="178" alt="Screenshot 2021-06-17 at 2 19 22 PM" src="https://user-images.githubusercontent.com/9653338/122364149-25f80080-cf77-11eb-807b-5ef27f251535.png">


**w/ `bestzip` (maximum ~27s)**
<img width="200" alt="Screenshot 2021-06-17 at 2 23 49 PM" src="https://user-images.githubusercontent.com/9653338/122364760-af0f3780-cf77-11eb-96d9-4b4a4fbea19e.png">

**Comment by floydspace** [comment]
> @floydspace What do you think about `bestzip`?

@vamche I'm very welcome for any improvements. Thanks for benchmarking it. Will check the PR.

**Comment by olup** [comment]
This is pretty good perfs !
