### ISSUE TITLE
Allow usage of esbuild plugins

### ISSUE THREAD

**Issue by thomaschaaf** [floydspace/serverless-esbuild#97]

**Comment by justin-prather** [comment]
I would also appreciate this, unless there is another way to ignore modules similar to webpacks ignorePlugin

**Comment by olup** [comment]
@justin-prather I might be mistaken, but isn't the `exclude` option used for exactly that ?

**Comment by justin-prather** [comment]
@olup yes and no

From my understanding, you can exclude individual files using the serverless.yml exclude section. In my case though, what's happening is that the build is failing on an optional dependency of one of my project's dependencies. specifically pg-native. A package called slonik tries to use pg-native and if it is not available falls back to the pg module.  the way i got around this with webpack was 
```
plugins: [
    new IgnorePlugin({
      resourceRegExp: /^pg-native$/,
    }),
  ],
```

there is an equivalent for esbuild but it doesn't appear on the surface at least to be usable with serverless-esbuild

**Comment by floydspace** [comment]
Hey @thomaschaaf, unfortunately, I cannot reproduce the build error with `slonik`, or it is a runtime issue?
maybe it's possible to use `exclude` option in pair with [inject](https://esbuild.github.io/api/#inject). According to the `inject` doc you could make desired behavior for global vars. Would be good If you could make a minimal reproducible example to understand the issue. Anyway plugin support is a nice to have feature imo. thank you

**Comment by justin-prather** [comment]
@floydspace looks like my issue was bubbling up from npm. Even though I'm not installing pg-native, it was still looking for the libpq dependency. Would still be nice to be able to just ignore that pattern and not have to install libpq
